
// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;

namespace PIKCV.DAL
{
	public class ComputerKnowledgeTypes : _ComputerKnowledgeTypes
	{

        //Tüm Bilgisayar Bilgisi Tiplerini Getir 
        public DataTable LoadAllML(bool IsDeleted)
        {
            SqlConnection conn = DBHelper.getConnection();
            SqlCommand cmd = DBHelper.getSprocCmd("_GetComputerKnowledgeTypesAll", conn);
            SqlDataAdapter da;
            SqlParameter param;
            DataTable dt = new DataTable();

            param = new SqlParameter("@IsDeleted", SqlDbType.Bit, 1);
            param.Direction = ParameterDirection.Input;
            param.Value = IsDeleted;
            cmd.Parameters.Add(param);

            da = new SqlDataAdapter(cmd);
            da.Fill(dt);
            return dt;
        }
	}
}
