
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class CustomProjectStates_ML : _CustomProjectStates_ML
	{
		public CustomProjectStates_ML()
		{
		
		}
	}
}
