
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class DriverLicenseTypes_ML : _DriverLicenseTypes_ML
	{
		public DriverLicenseTypes_ML()
		{
		
		}
	}
}
