
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class EducationStates_ML : _EducationStates_ML
	{
		public EducationStates_ML()
		{
		
		}
	}
}
