
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class ForeignLanguages_ML : _ForeignLanguages_ML
	{
		public ForeignLanguages_ML()
		{
		
		}
	}
}
