
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class InterviewPikcvProperties_ML : _InterviewPikcvProperties_ML
	{
		public InterviewPikcvProperties_ML()
		{
		
		}
	}
}
