
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class MilitaryStates_ML : _MilitaryStates_ML
	{
		public MilitaryStates_ML()
		{
		
		}
	}
}
