
// Generated by MyGeneration Version # (1.3.0.0)

using System;

namespace PIKCV.DAL
{
	public class SystemDraftMessages : _SystemDraftMessages
	{
		public SystemDraftMessages()
		{
		
		}
	}
}
