
// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;

namespace PIKCV.DAL
{
	public class TestTotalScoreScale : _TestTotalScoreScale
	{
        //Test Toplam Skoru Bilgileri
        public DataTable GetTestTotalScoreInfo(float TotalPoint, int LanguageID, int EmployeeType)
        {
            SqlConnection conn = DBHelper.getConnection();
            SqlCommand cmd = DBHelper.getSprocCmd("_GetTestTotalScoreInfo", conn);
            SqlDataAdapter da;
            SqlParameter param;
            DataTable dt = new DataTable();

            param = new SqlParameter("@TOTALPOINT", SqlDbType.Float);
            param.Direction = ParameterDirection.Input;
            param.Value = TotalPoint;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@LanguageID", SqlDbType.Int, 4);
            param.Direction = ParameterDirection.Input;
            param.Value = @LanguageID;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@EmployeeType", SqlDbType.Int, 4);
            param.Direction = ParameterDirection.Input;
            param.Value = EmployeeType;
            cmd.Parameters.Add(param);

            da = new SqlDataAdapter(cmd);
            da.Fill(dt);
            return dt;
        }
	}
}
