
// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;

namespace PIKCV.DAL
{
    public class User : _User
    {
        //Arama Sonuçlarý
        public DataTable GetEmployeeSearchResults(string Gender, string AgeRange, string MaritalStates, string MilitaryStates,
            int DriverLicenceTypes, bool Handicapped, bool Convicted,
            bool MartyrRelative,
            bool TerrorAggrieved,
            string Countries,
            string TurkeyCities,
            string EducationLevels,
            string EducationStates,
            string HighSchoolEducationLevels,
            int HighSchoolTypes,
            string UniversityEducationLevels,
            int UniversityNames,
            int DepartmentNames,
            string Sectors,
            string Positions,
            string Experience,
            string LabouringTypes,
            string ForeignLanguages,
            string ComputerKnowledgeTypes,
            string SectorsDesired,
            string PositionsDesired,
            string CountriesDesired,
            string CitiesDesired,
            string LabouringTypesDesired,
            int EmployeeSearchType,
            int CompanyID,
            int JobID, 
            string ApplicationStatus)
        {
            SqlConnection conn = DBHelper.getConnection();
            SqlCommand cmd = DBHelper.getSprocCmd("_GetEmployeeSearchResults2", conn);
            SqlDataAdapter da;
            SqlParameter param;
            DataTable dt = new DataTable();

            param = new SqlParameter("@xGender", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = Gender;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xAgeRange", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = AgeRange;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xMaritalStates", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = MaritalStates;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xMilitaryStates", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = MilitaryStates;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@DriverLicenceTypes", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = DriverLicenceTypes;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@Handicapped", SqlDbType.Bit);
            param.Direction = ParameterDirection.Input;
            param.Value = Handicapped;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@Convicted", SqlDbType.Bit);
            param.Direction = ParameterDirection.Input;
            param.Value = Convicted;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@MartyrRelative", SqlDbType.Bit);
            param.Direction = ParameterDirection.Input;
            param.Value = MartyrRelative;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@TerrorAggrieved", SqlDbType.Bit);
            param.Direction = ParameterDirection.Input;
            param.Value = TerrorAggrieved;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xCountries", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = Countries;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xTurkeyCities", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = TurkeyCities;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xEducationLevels", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = EducationLevels;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xEducationStates", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = EducationStates;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xHighSchoolEducationLevels", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = HighSchoolEducationLevels;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@HighSchoolTypes", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = HighSchoolTypes;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xUniversityEducationLevels", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = UniversityEducationLevels;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@UniversityNames", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = UniversityNames;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@DepartmentNames", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = DepartmentNames;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xSectors", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = Sectors;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xPositions", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = Positions;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xExperience", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = Experience;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xLabouringTypes", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = LabouringTypes;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xForeignLanguages", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = ForeignLanguages;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xComputerKnowledgeTypes", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = ComputerKnowledgeTypes;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xSectorsDesired", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = SectorsDesired;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xPositionsDesired", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = PositionsDesired;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xCountriesDesired", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = CountriesDesired;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xCitiesDesired", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = CitiesDesired;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xLabouringTypesDesired", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = LabouringTypesDesired;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@EmployeeSearchType", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = EmployeeSearchType;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@CompanyID", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = CompanyID;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@JobID", SqlDbType.Int);
            param.Direction = ParameterDirection.Input;
            param.Value = JobID;
            cmd.Parameters.Add(param);

            param = new SqlParameter("@xApplicationStatus", SqlDbType.VarChar);
            param.Direction = ParameterDirection.Input;
            param.Value = ApplicationStatus;
            cmd.Parameters.Add(param);

            da = new SqlDataAdapter(cmd);
            da.Fill(dt);
            return dt;
        }
    }
}
