<meta http-equiv="Content-Type" content="text/html; charset=windows-1254;" />
<meta http-equiv="Content-Language" content="tr" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="keywords" content="İNSAN KAYNAKLARI, Eleman Arıyorum, İş Arıyorum" />
<meta name="description" content="PIKCV" />
<meta name="Author" content="by Caretta.Net" />
<meta name="Copyright" content="PIKCV" />
<meta name="reply-to" content="info@pikcv.com" />
<meta name="robots" content="ALL" />
<meta name="revisit-after" content="1" />
<meta name="Rating" content="General" />
<meta name="Distribution" content="Global" />
<meta name="Classification" content="PIKCV" />
<meta name="Pragma" content="no-cache" />
<meta name="mssmarttagspreventparsing" content="true" />