
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _Articles : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _Articles()
		{
			this.QuerySource = "Articles";
			this.MappingName = "Articles";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ArticlesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ArticleID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ArticleID, ArticleID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ArticlesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ArticleID
			{
				get
				{
					return new SqlParameter("@ArticleID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArticleTypeCode
			{
				get
				{
					return new SqlParameter("@ArticleTypeCode", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArticleTitle
			{
				get
				{
					return new SqlParameter("@ArticleTitle", SqlDbType.NVarChar, 128);
				}
			}
			
			public static SqlParameter ArticleAbstract
			{
				get
				{
					return new SqlParameter("@ArticleAbstract", SqlDbType.NVarChar, 800);
				}
			}
			
			public static SqlParameter ArticleBody
			{
				get
				{
					return new SqlParameter("@ArticleBody", SqlDbType.NText, 1073741823);
				}
			}
			
			public static SqlParameter PhotoFileName
			{
				get
				{
					return new SqlParameter("@PhotoFileName", SqlDbType.NVarChar, 64);
				}
			}
			
			public static SqlParameter CreateDate
			{
				get
				{
					return new SqlParameter("@CreateDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ModifyDate
			{
				get
				{
					return new SqlParameter("@ModifyDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter UpdatedBy
			{
				get
				{
					return new SqlParameter("@UpdatedBy", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IsMain
			{
				get
				{
					return new SqlParameter("@IsMain", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsDeleted
			{
				get
				{
					return new SqlParameter("@IsDeleted", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ArticleID = "ArticleID";
            public const string ArticleTypeCode = "ArticleTypeCode";
            public const string ArticleTitle = "ArticleTitle";
            public const string ArticleAbstract = "ArticleAbstract";
            public const string ArticleBody = "ArticleBody";
            public const string PhotoFileName = "PhotoFileName";
            public const string CreateDate = "CreateDate";
            public const string ModifyDate = "ModifyDate";
            public const string UpdatedBy = "UpdatedBy";
            public const string IsMain = "IsMain";
            public const string IsDeleted = "IsDeleted";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ArticleID] = _Articles.PropertyNames.ArticleID;
					ht[ArticleTypeCode] = _Articles.PropertyNames.ArticleTypeCode;
					ht[ArticleTitle] = _Articles.PropertyNames.ArticleTitle;
					ht[ArticleAbstract] = _Articles.PropertyNames.ArticleAbstract;
					ht[ArticleBody] = _Articles.PropertyNames.ArticleBody;
					ht[PhotoFileName] = _Articles.PropertyNames.PhotoFileName;
					ht[CreateDate] = _Articles.PropertyNames.CreateDate;
					ht[ModifyDate] = _Articles.PropertyNames.ModifyDate;
					ht[UpdatedBy] = _Articles.PropertyNames.UpdatedBy;
					ht[IsMain] = _Articles.PropertyNames.IsMain;
					ht[IsDeleted] = _Articles.PropertyNames.IsDeleted;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ArticleID = "ArticleID";
            public const string ArticleTypeCode = "ArticleTypeCode";
            public const string ArticleTitle = "ArticleTitle";
            public const string ArticleAbstract = "ArticleAbstract";
            public const string ArticleBody = "ArticleBody";
            public const string PhotoFileName = "PhotoFileName";
            public const string CreateDate = "CreateDate";
            public const string ModifyDate = "ModifyDate";
            public const string UpdatedBy = "UpdatedBy";
            public const string IsMain = "IsMain";
            public const string IsDeleted = "IsDeleted";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ArticleID] = _Articles.ColumnNames.ArticleID;
					ht[ArticleTypeCode] = _Articles.ColumnNames.ArticleTypeCode;
					ht[ArticleTitle] = _Articles.ColumnNames.ArticleTitle;
					ht[ArticleAbstract] = _Articles.ColumnNames.ArticleAbstract;
					ht[ArticleBody] = _Articles.ColumnNames.ArticleBody;
					ht[PhotoFileName] = _Articles.ColumnNames.PhotoFileName;
					ht[CreateDate] = _Articles.ColumnNames.CreateDate;
					ht[ModifyDate] = _Articles.ColumnNames.ModifyDate;
					ht[UpdatedBy] = _Articles.ColumnNames.UpdatedBy;
					ht[IsMain] = _Articles.ColumnNames.IsMain;
					ht[IsDeleted] = _Articles.ColumnNames.IsDeleted;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ArticleID = "s_ArticleID";
            public const string ArticleTypeCode = "s_ArticleTypeCode";
            public const string ArticleTitle = "s_ArticleTitle";
            public const string ArticleAbstract = "s_ArticleAbstract";
            public const string ArticleBody = "s_ArticleBody";
            public const string PhotoFileName = "s_PhotoFileName";
            public const string CreateDate = "s_CreateDate";
            public const string ModifyDate = "s_ModifyDate";
            public const string UpdatedBy = "s_UpdatedBy";
            public const string IsMain = "s_IsMain";
            public const string IsDeleted = "s_IsDeleted";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ArticleID
	    {
			get
	        {
				return base.Getint(ColumnNames.ArticleID);
			}
			set
	        {
				base.Setint(ColumnNames.ArticleID, value);
			}
		}

		public virtual int ArticleTypeCode
	    {
			get
	        {
				return base.Getint(ColumnNames.ArticleTypeCode);
			}
			set
	        {
				base.Setint(ColumnNames.ArticleTypeCode, value);
			}
		}

		public virtual string ArticleTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArticleTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.ArticleTitle, value);
			}
		}

		public virtual string ArticleAbstract
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArticleAbstract);
			}
			set
	        {
				base.Setstring(ColumnNames.ArticleAbstract, value);
			}
		}

		public virtual string ArticleBody
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArticleBody);
			}
			set
	        {
				base.Setstring(ColumnNames.ArticleBody, value);
			}
		}

		public virtual string PhotoFileName
	    {
			get
	        {
				return base.Getstring(ColumnNames.PhotoFileName);
			}
			set
	        {
				base.Setstring(ColumnNames.PhotoFileName, value);
			}
		}

		public virtual DateTime CreateDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CreateDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CreateDate, value);
			}
		}

		public virtual DateTime ModifyDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ModifyDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ModifyDate, value);
			}
		}

		public virtual int UpdatedBy
	    {
			get
	        {
				return base.Getint(ColumnNames.UpdatedBy);
			}
			set
	        {
				base.Setint(ColumnNames.UpdatedBy, value);
			}
		}

		public virtual bool IsMain
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsMain);
			}
			set
	        {
				base.Setbool(ColumnNames.IsMain, value);
			}
		}

		public virtual bool IsDeleted
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsDeleted);
			}
			set
	        {
				base.Setbool(ColumnNames.IsDeleted, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ArticleID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArticleID) ? string.Empty : base.GetintAsString(ColumnNames.ArticleID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArticleID);
				else
					this.ArticleID = base.SetintAsString(ColumnNames.ArticleID, value);
			}
		}

		public virtual string s_ArticleTypeCode
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArticleTypeCode) ? string.Empty : base.GetintAsString(ColumnNames.ArticleTypeCode);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArticleTypeCode);
				else
					this.ArticleTypeCode = base.SetintAsString(ColumnNames.ArticleTypeCode, value);
			}
		}

		public virtual string s_ArticleTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArticleTitle) ? string.Empty : base.GetstringAsString(ColumnNames.ArticleTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArticleTitle);
				else
					this.ArticleTitle = base.SetstringAsString(ColumnNames.ArticleTitle, value);
			}
		}

		public virtual string s_ArticleAbstract
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArticleAbstract) ? string.Empty : base.GetstringAsString(ColumnNames.ArticleAbstract);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArticleAbstract);
				else
					this.ArticleAbstract = base.SetstringAsString(ColumnNames.ArticleAbstract, value);
			}
		}

		public virtual string s_ArticleBody
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArticleBody) ? string.Empty : base.GetstringAsString(ColumnNames.ArticleBody);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArticleBody);
				else
					this.ArticleBody = base.SetstringAsString(ColumnNames.ArticleBody, value);
			}
		}

		public virtual string s_PhotoFileName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PhotoFileName) ? string.Empty : base.GetstringAsString(ColumnNames.PhotoFileName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PhotoFileName);
				else
					this.PhotoFileName = base.SetstringAsString(ColumnNames.PhotoFileName, value);
			}
		}

		public virtual string s_CreateDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreateDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CreateDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreateDate);
				else
					this.CreateDate = base.SetDateTimeAsString(ColumnNames.CreateDate, value);
			}
		}

		public virtual string s_ModifyDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifyDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ModifyDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifyDate);
				else
					this.ModifyDate = base.SetDateTimeAsString(ColumnNames.ModifyDate, value);
			}
		}

		public virtual string s_UpdatedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UpdatedBy) ? string.Empty : base.GetintAsString(ColumnNames.UpdatedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UpdatedBy);
				else
					this.UpdatedBy = base.SetintAsString(ColumnNames.UpdatedBy, value);
			}
		}

		public virtual string s_IsMain
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsMain) ? string.Empty : base.GetboolAsString(ColumnNames.IsMain);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsMain);
				else
					this.IsMain = base.SetboolAsString(ColumnNames.IsMain, value);
			}
		}

		public virtual string s_IsDeleted
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsDeleted) ? string.Empty : base.GetboolAsString(ColumnNames.IsDeleted);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsDeleted);
				else
					this.IsDeleted = base.SetboolAsString(ColumnNames.IsDeleted, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ArticleID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArticleID, Parameters.ArticleID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArticleTypeCode
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArticleTypeCode, Parameters.ArticleTypeCode);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArticleTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArticleTitle, Parameters.ArticleTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArticleAbstract
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArticleAbstract, Parameters.ArticleAbstract);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArticleBody
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArticleBody, Parameters.ArticleBody);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PhotoFileName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PhotoFileName, Parameters.PhotoFileName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreateDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreateDate, Parameters.CreateDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifyDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifyDate, Parameters.ModifyDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UpdatedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UpdatedBy, Parameters.UpdatedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsMain
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsMain, Parameters.IsMain);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsDeleted
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsDeleted, Parameters.IsDeleted);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ArticleID
		    {
				get
		        {
					if(_ArticleID_W == null)
	        	    {
						_ArticleID_W = TearOff.ArticleID;
					}
					return _ArticleID_W;
				}
			}

			public WhereParameter ArticleTypeCode
		    {
				get
		        {
					if(_ArticleTypeCode_W == null)
	        	    {
						_ArticleTypeCode_W = TearOff.ArticleTypeCode;
					}
					return _ArticleTypeCode_W;
				}
			}

			public WhereParameter ArticleTitle
		    {
				get
		        {
					if(_ArticleTitle_W == null)
	        	    {
						_ArticleTitle_W = TearOff.ArticleTitle;
					}
					return _ArticleTitle_W;
				}
			}

			public WhereParameter ArticleAbstract
		    {
				get
		        {
					if(_ArticleAbstract_W == null)
	        	    {
						_ArticleAbstract_W = TearOff.ArticleAbstract;
					}
					return _ArticleAbstract_W;
				}
			}

			public WhereParameter ArticleBody
		    {
				get
		        {
					if(_ArticleBody_W == null)
	        	    {
						_ArticleBody_W = TearOff.ArticleBody;
					}
					return _ArticleBody_W;
				}
			}

			public WhereParameter PhotoFileName
		    {
				get
		        {
					if(_PhotoFileName_W == null)
	        	    {
						_PhotoFileName_W = TearOff.PhotoFileName;
					}
					return _PhotoFileName_W;
				}
			}

			public WhereParameter CreateDate
		    {
				get
		        {
					if(_CreateDate_W == null)
	        	    {
						_CreateDate_W = TearOff.CreateDate;
					}
					return _CreateDate_W;
				}
			}

			public WhereParameter ModifyDate
		    {
				get
		        {
					if(_ModifyDate_W == null)
	        	    {
						_ModifyDate_W = TearOff.ModifyDate;
					}
					return _ModifyDate_W;
				}
			}

			public WhereParameter UpdatedBy
		    {
				get
		        {
					if(_UpdatedBy_W == null)
	        	    {
						_UpdatedBy_W = TearOff.UpdatedBy;
					}
					return _UpdatedBy_W;
				}
			}

			public WhereParameter IsMain
		    {
				get
		        {
					if(_IsMain_W == null)
	        	    {
						_IsMain_W = TearOff.IsMain;
					}
					return _IsMain_W;
				}
			}

			public WhereParameter IsDeleted
		    {
				get
		        {
					if(_IsDeleted_W == null)
	        	    {
						_IsDeleted_W = TearOff.IsDeleted;
					}
					return _IsDeleted_W;
				}
			}

			private WhereParameter _ArticleID_W = null;
			private WhereParameter _ArticleTypeCode_W = null;
			private WhereParameter _ArticleTitle_W = null;
			private WhereParameter _ArticleAbstract_W = null;
			private WhereParameter _ArticleBody_W = null;
			private WhereParameter _PhotoFileName_W = null;
			private WhereParameter _CreateDate_W = null;
			private WhereParameter _ModifyDate_W = null;
			private WhereParameter _UpdatedBy_W = null;
			private WhereParameter _IsMain_W = null;
			private WhereParameter _IsDeleted_W = null;

			public void WhereClauseReset()
			{
				_ArticleID_W = null;
				_ArticleTypeCode_W = null;
				_ArticleTitle_W = null;
				_ArticleAbstract_W = null;
				_ArticleBody_W = null;
				_PhotoFileName_W = null;
				_CreateDate_W = null;
				_ModifyDate_W = null;
				_UpdatedBy_W = null;
				_IsMain_W = null;
				_IsDeleted_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ArticleID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArticleID, Parameters.ArticleID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArticleTypeCode
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArticleTypeCode, Parameters.ArticleTypeCode);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArticleTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArticleTitle, Parameters.ArticleTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArticleAbstract
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArticleAbstract, Parameters.ArticleAbstract);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArticleBody
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArticleBody, Parameters.ArticleBody);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PhotoFileName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PhotoFileName, Parameters.PhotoFileName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreateDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreateDate, Parameters.CreateDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifyDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifyDate, Parameters.ModifyDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UpdatedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UpdatedBy, Parameters.UpdatedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsMain
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsMain, Parameters.IsMain);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsDeleted
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsDeleted, Parameters.IsDeleted);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ArticleID
		    {
				get
		        {
					if(_ArticleID_W == null)
	        	    {
						_ArticleID_W = TearOff.ArticleID;
					}
					return _ArticleID_W;
				}
			}

			public AggregateParameter ArticleTypeCode
		    {
				get
		        {
					if(_ArticleTypeCode_W == null)
	        	    {
						_ArticleTypeCode_W = TearOff.ArticleTypeCode;
					}
					return _ArticleTypeCode_W;
				}
			}

			public AggregateParameter ArticleTitle
		    {
				get
		        {
					if(_ArticleTitle_W == null)
	        	    {
						_ArticleTitle_W = TearOff.ArticleTitle;
					}
					return _ArticleTitle_W;
				}
			}

			public AggregateParameter ArticleAbstract
		    {
				get
		        {
					if(_ArticleAbstract_W == null)
	        	    {
						_ArticleAbstract_W = TearOff.ArticleAbstract;
					}
					return _ArticleAbstract_W;
				}
			}

			public AggregateParameter ArticleBody
		    {
				get
		        {
					if(_ArticleBody_W == null)
	        	    {
						_ArticleBody_W = TearOff.ArticleBody;
					}
					return _ArticleBody_W;
				}
			}

			public AggregateParameter PhotoFileName
		    {
				get
		        {
					if(_PhotoFileName_W == null)
	        	    {
						_PhotoFileName_W = TearOff.PhotoFileName;
					}
					return _PhotoFileName_W;
				}
			}

			public AggregateParameter CreateDate
		    {
				get
		        {
					if(_CreateDate_W == null)
	        	    {
						_CreateDate_W = TearOff.CreateDate;
					}
					return _CreateDate_W;
				}
			}

			public AggregateParameter ModifyDate
		    {
				get
		        {
					if(_ModifyDate_W == null)
	        	    {
						_ModifyDate_W = TearOff.ModifyDate;
					}
					return _ModifyDate_W;
				}
			}

			public AggregateParameter UpdatedBy
		    {
				get
		        {
					if(_UpdatedBy_W == null)
	        	    {
						_UpdatedBy_W = TearOff.UpdatedBy;
					}
					return _UpdatedBy_W;
				}
			}

			public AggregateParameter IsMain
		    {
				get
		        {
					if(_IsMain_W == null)
	        	    {
						_IsMain_W = TearOff.IsMain;
					}
					return _IsMain_W;
				}
			}

			public AggregateParameter IsDeleted
		    {
				get
		        {
					if(_IsDeleted_W == null)
	        	    {
						_IsDeleted_W = TearOff.IsDeleted;
					}
					return _IsDeleted_W;
				}
			}

			private AggregateParameter _ArticleID_W = null;
			private AggregateParameter _ArticleTypeCode_W = null;
			private AggregateParameter _ArticleTitle_W = null;
			private AggregateParameter _ArticleAbstract_W = null;
			private AggregateParameter _ArticleBody_W = null;
			private AggregateParameter _PhotoFileName_W = null;
			private AggregateParameter _CreateDate_W = null;
			private AggregateParameter _ModifyDate_W = null;
			private AggregateParameter _UpdatedBy_W = null;
			private AggregateParameter _IsMain_W = null;
			private AggregateParameter _IsDeleted_W = null;

			public void AggregateClauseReset()
			{
				_ArticleID_W = null;
				_ArticleTypeCode_W = null;
				_ArticleTitle_W = null;
				_ArticleAbstract_W = null;
				_ArticleBody_W = null;
				_PhotoFileName_W = null;
				_CreateDate_W = null;
				_ModifyDate_W = null;
				_UpdatedBy_W = null;
				_IsMain_W = null;
				_IsDeleted_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ArticlesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ArticleID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ArticlesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ArticlesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ArticleID);
			p.SourceColumn = ColumnNames.ArticleID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ArticleID);
			p.SourceColumn = ColumnNames.ArticleID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArticleTypeCode);
			p.SourceColumn = ColumnNames.ArticleTypeCode;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArticleTitle);
			p.SourceColumn = ColumnNames.ArticleTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArticleAbstract);
			p.SourceColumn = ColumnNames.ArticleAbstract;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArticleBody);
			p.SourceColumn = ColumnNames.ArticleBody;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PhotoFileName);
			p.SourceColumn = ColumnNames.PhotoFileName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreateDate);
			p.SourceColumn = ColumnNames.CreateDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifyDate);
			p.SourceColumn = ColumnNames.ModifyDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UpdatedBy);
			p.SourceColumn = ColumnNames.UpdatedBy;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsMain);
			p.SourceColumn = ColumnNames.IsMain;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsDeleted);
			p.SourceColumn = ColumnNames.IsDeleted;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
