
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _ItemCredits : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _ItemCredits()
		{
			this.QuerySource = "ItemCredits";
			this.MappingName = "ItemCredits";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ItemCreditsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ItemCreditID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ItemCreditID, ItemCreditID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ItemCreditsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ItemCreditID
			{
				get
				{
					return new SqlParameter("@ItemCreditID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ItemName
			{
				get
				{
					return new SqlParameter("@ItemName", SqlDbType.NVarChar, 64);
				}
			}
			
			public static SqlParameter GroupName
			{
				get
				{
					return new SqlParameter("@GroupName", SqlDbType.NVarChar, 32);
				}
			}
			
			public static SqlParameter SortOrder
			{
				get
				{
					return new SqlParameter("@SortOrder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Credit
			{
				get
				{
					return new SqlParameter("@Credit", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ModifiedDate
			{
				get
				{
					return new SqlParameter("@ModifiedDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter UpdatedBy
			{
				get
				{
					return new SqlParameter("@UpdatedBy", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ItemCreditID = "ItemCreditID";
            public const string ItemName = "ItemName";
            public const string GroupName = "GroupName";
            public const string SortOrder = "SortOrder";
            public const string Credit = "Credit";
            public const string ModifiedDate = "ModifiedDate";
            public const string UpdatedBy = "UpdatedBy";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ItemCreditID] = _ItemCredits.PropertyNames.ItemCreditID;
					ht[ItemName] = _ItemCredits.PropertyNames.ItemName;
					ht[GroupName] = _ItemCredits.PropertyNames.GroupName;
					ht[SortOrder] = _ItemCredits.PropertyNames.SortOrder;
					ht[Credit] = _ItemCredits.PropertyNames.Credit;
					ht[ModifiedDate] = _ItemCredits.PropertyNames.ModifiedDate;
					ht[UpdatedBy] = _ItemCredits.PropertyNames.UpdatedBy;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ItemCreditID = "ItemCreditID";
            public const string ItemName = "ItemName";
            public const string GroupName = "GroupName";
            public const string SortOrder = "SortOrder";
            public const string Credit = "Credit";
            public const string ModifiedDate = "ModifiedDate";
            public const string UpdatedBy = "UpdatedBy";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ItemCreditID] = _ItemCredits.ColumnNames.ItemCreditID;
					ht[ItemName] = _ItemCredits.ColumnNames.ItemName;
					ht[GroupName] = _ItemCredits.ColumnNames.GroupName;
					ht[SortOrder] = _ItemCredits.ColumnNames.SortOrder;
					ht[Credit] = _ItemCredits.ColumnNames.Credit;
					ht[ModifiedDate] = _ItemCredits.ColumnNames.ModifiedDate;
					ht[UpdatedBy] = _ItemCredits.ColumnNames.UpdatedBy;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ItemCreditID = "s_ItemCreditID";
            public const string ItemName = "s_ItemName";
            public const string GroupName = "s_GroupName";
            public const string SortOrder = "s_SortOrder";
            public const string Credit = "s_Credit";
            public const string ModifiedDate = "s_ModifiedDate";
            public const string UpdatedBy = "s_UpdatedBy";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ItemCreditID
	    {
			get
	        {
				return base.Getint(ColumnNames.ItemCreditID);
			}
			set
	        {
				base.Setint(ColumnNames.ItemCreditID, value);
			}
		}

		public virtual string ItemName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ItemName);
			}
			set
	        {
				base.Setstring(ColumnNames.ItemName, value);
			}
		}

		public virtual string GroupName
	    {
			get
	        {
				return base.Getstring(ColumnNames.GroupName);
			}
			set
	        {
				base.Setstring(ColumnNames.GroupName, value);
			}
		}

		public virtual int SortOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.SortOrder);
			}
			set
	        {
				base.Setint(ColumnNames.SortOrder, value);
			}
		}

		public virtual int Credit
	    {
			get
	        {
				return base.Getint(ColumnNames.Credit);
			}
			set
	        {
				base.Setint(ColumnNames.Credit, value);
			}
		}

		public virtual DateTime ModifiedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ModifiedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual int UpdatedBy
	    {
			get
	        {
				return base.Getint(ColumnNames.UpdatedBy);
			}
			set
	        {
				base.Setint(ColumnNames.UpdatedBy, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ItemCreditID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ItemCreditID) ? string.Empty : base.GetintAsString(ColumnNames.ItemCreditID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ItemCreditID);
				else
					this.ItemCreditID = base.SetintAsString(ColumnNames.ItemCreditID, value);
			}
		}

		public virtual string s_ItemName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ItemName) ? string.Empty : base.GetstringAsString(ColumnNames.ItemName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ItemName);
				else
					this.ItemName = base.SetstringAsString(ColumnNames.ItemName, value);
			}
		}

		public virtual string s_GroupName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GroupName) ? string.Empty : base.GetstringAsString(ColumnNames.GroupName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GroupName);
				else
					this.GroupName = base.SetstringAsString(ColumnNames.GroupName, value);
			}
		}

		public virtual string s_SortOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SortOrder) ? string.Empty : base.GetintAsString(ColumnNames.SortOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SortOrder);
				else
					this.SortOrder = base.SetintAsString(ColumnNames.SortOrder, value);
			}
		}

		public virtual string s_Credit
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Credit) ? string.Empty : base.GetintAsString(ColumnNames.Credit);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Credit);
				else
					this.Credit = base.SetintAsString(ColumnNames.Credit, value);
			}
		}

		public virtual string s_ModifiedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifiedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ModifiedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifiedDate);
				else
					this.ModifiedDate = base.SetDateTimeAsString(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual string s_UpdatedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UpdatedBy) ? string.Empty : base.GetintAsString(ColumnNames.UpdatedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UpdatedBy);
				else
					this.UpdatedBy = base.SetintAsString(ColumnNames.UpdatedBy, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ItemCreditID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ItemCreditID, Parameters.ItemCreditID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ItemName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ItemName, Parameters.ItemName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GroupName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GroupName, Parameters.GroupName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SortOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SortOrder, Parameters.SortOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Credit
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Credit, Parameters.Credit);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifiedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UpdatedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UpdatedBy, Parameters.UpdatedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ItemCreditID
		    {
				get
		        {
					if(_ItemCreditID_W == null)
	        	    {
						_ItemCreditID_W = TearOff.ItemCreditID;
					}
					return _ItemCreditID_W;
				}
			}

			public WhereParameter ItemName
		    {
				get
		        {
					if(_ItemName_W == null)
	        	    {
						_ItemName_W = TearOff.ItemName;
					}
					return _ItemName_W;
				}
			}

			public WhereParameter GroupName
		    {
				get
		        {
					if(_GroupName_W == null)
	        	    {
						_GroupName_W = TearOff.GroupName;
					}
					return _GroupName_W;
				}
			}

			public WhereParameter SortOrder
		    {
				get
		        {
					if(_SortOrder_W == null)
	        	    {
						_SortOrder_W = TearOff.SortOrder;
					}
					return _SortOrder_W;
				}
			}

			public WhereParameter Credit
		    {
				get
		        {
					if(_Credit_W == null)
	        	    {
						_Credit_W = TearOff.Credit;
					}
					return _Credit_W;
				}
			}

			public WhereParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public WhereParameter UpdatedBy
		    {
				get
		        {
					if(_UpdatedBy_W == null)
	        	    {
						_UpdatedBy_W = TearOff.UpdatedBy;
					}
					return _UpdatedBy_W;
				}
			}

			private WhereParameter _ItemCreditID_W = null;
			private WhereParameter _ItemName_W = null;
			private WhereParameter _GroupName_W = null;
			private WhereParameter _SortOrder_W = null;
			private WhereParameter _Credit_W = null;
			private WhereParameter _ModifiedDate_W = null;
			private WhereParameter _UpdatedBy_W = null;

			public void WhereClauseReset()
			{
				_ItemCreditID_W = null;
				_ItemName_W = null;
				_GroupName_W = null;
				_SortOrder_W = null;
				_Credit_W = null;
				_ModifiedDate_W = null;
				_UpdatedBy_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ItemCreditID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ItemCreditID, Parameters.ItemCreditID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ItemName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ItemName, Parameters.ItemName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GroupName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GroupName, Parameters.GroupName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SortOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SortOrder, Parameters.SortOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Credit
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Credit, Parameters.Credit);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifiedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UpdatedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UpdatedBy, Parameters.UpdatedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ItemCreditID
		    {
				get
		        {
					if(_ItemCreditID_W == null)
	        	    {
						_ItemCreditID_W = TearOff.ItemCreditID;
					}
					return _ItemCreditID_W;
				}
			}

			public AggregateParameter ItemName
		    {
				get
		        {
					if(_ItemName_W == null)
	        	    {
						_ItemName_W = TearOff.ItemName;
					}
					return _ItemName_W;
				}
			}

			public AggregateParameter GroupName
		    {
				get
		        {
					if(_GroupName_W == null)
	        	    {
						_GroupName_W = TearOff.GroupName;
					}
					return _GroupName_W;
				}
			}

			public AggregateParameter SortOrder
		    {
				get
		        {
					if(_SortOrder_W == null)
	        	    {
						_SortOrder_W = TearOff.SortOrder;
					}
					return _SortOrder_W;
				}
			}

			public AggregateParameter Credit
		    {
				get
		        {
					if(_Credit_W == null)
	        	    {
						_Credit_W = TearOff.Credit;
					}
					return _Credit_W;
				}
			}

			public AggregateParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public AggregateParameter UpdatedBy
		    {
				get
		        {
					if(_UpdatedBy_W == null)
	        	    {
						_UpdatedBy_W = TearOff.UpdatedBy;
					}
					return _UpdatedBy_W;
				}
			}

			private AggregateParameter _ItemCreditID_W = null;
			private AggregateParameter _ItemName_W = null;
			private AggregateParameter _GroupName_W = null;
			private AggregateParameter _SortOrder_W = null;
			private AggregateParameter _Credit_W = null;
			private AggregateParameter _ModifiedDate_W = null;
			private AggregateParameter _UpdatedBy_W = null;

			public void AggregateClauseReset()
			{
				_ItemCreditID_W = null;
				_ItemName_W = null;
				_GroupName_W = null;
				_SortOrder_W = null;
				_Credit_W = null;
				_ModifiedDate_W = null;
				_UpdatedBy_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ItemCreditsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ItemCreditID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ItemCreditsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ItemCreditsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ItemCreditID);
			p.SourceColumn = ColumnNames.ItemCreditID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ItemCreditID);
			p.SourceColumn = ColumnNames.ItemCreditID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ItemName);
			p.SourceColumn = ColumnNames.ItemName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GroupName);
			p.SourceColumn = ColumnNames.GroupName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SortOrder);
			p.SourceColumn = ColumnNames.SortOrder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Credit);
			p.SourceColumn = ColumnNames.Credit;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifiedDate);
			p.SourceColumn = ColumnNames.ModifiedDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UpdatedBy);
			p.SourceColumn = ColumnNames.UpdatedBy;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
