
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _JobChoiceForeignLanguage : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _JobChoiceForeignLanguage()
		{
			this.QuerySource = "JobChoiceForeignLanguage";
			this.MappingName = "JobChoiceForeignLanguage";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_JobChoiceForeignLanguageLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int RowID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.RowID, RowID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_JobChoiceForeignLanguageLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter RowID
			{
				get
				{
					return new SqlParameter("@RowID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter JobID
			{
				get
				{
					return new SqlParameter("@JobID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ForeignLanguageID
			{
				get
				{
					return new SqlParameter("@ForeignLanguageID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ReadLevel
			{
				get
				{
					return new SqlParameter("@ReadLevel", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter WriteLevel
			{
				get
				{
					return new SqlParameter("@WriteLevel", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SpeakLevel
			{
				get
				{
					return new SqlParameter("@SpeakLevel", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Points
			{
				get
				{
					return new SqlParameter("@Points", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string RowID = "RowID";
            public const string JobID = "JobID";
            public const string ForeignLanguageID = "ForeignLanguageID";
            public const string ReadLevel = "ReadLevel";
            public const string WriteLevel = "WriteLevel";
            public const string SpeakLevel = "SpeakLevel";
            public const string Points = "Points";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RowID] = _JobChoiceForeignLanguage.PropertyNames.RowID;
					ht[JobID] = _JobChoiceForeignLanguage.PropertyNames.JobID;
					ht[ForeignLanguageID] = _JobChoiceForeignLanguage.PropertyNames.ForeignLanguageID;
					ht[ReadLevel] = _JobChoiceForeignLanguage.PropertyNames.ReadLevel;
					ht[WriteLevel] = _JobChoiceForeignLanguage.PropertyNames.WriteLevel;
					ht[SpeakLevel] = _JobChoiceForeignLanguage.PropertyNames.SpeakLevel;
					ht[Points] = _JobChoiceForeignLanguage.PropertyNames.Points;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string RowID = "RowID";
            public const string JobID = "JobID";
            public const string ForeignLanguageID = "ForeignLanguageID";
            public const string ReadLevel = "ReadLevel";
            public const string WriteLevel = "WriteLevel";
            public const string SpeakLevel = "SpeakLevel";
            public const string Points = "Points";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RowID] = _JobChoiceForeignLanguage.ColumnNames.RowID;
					ht[JobID] = _JobChoiceForeignLanguage.ColumnNames.JobID;
					ht[ForeignLanguageID] = _JobChoiceForeignLanguage.ColumnNames.ForeignLanguageID;
					ht[ReadLevel] = _JobChoiceForeignLanguage.ColumnNames.ReadLevel;
					ht[WriteLevel] = _JobChoiceForeignLanguage.ColumnNames.WriteLevel;
					ht[SpeakLevel] = _JobChoiceForeignLanguage.ColumnNames.SpeakLevel;
					ht[Points] = _JobChoiceForeignLanguage.ColumnNames.Points;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string RowID = "s_RowID";
            public const string JobID = "s_JobID";
            public const string ForeignLanguageID = "s_ForeignLanguageID";
            public const string ReadLevel = "s_ReadLevel";
            public const string WriteLevel = "s_WriteLevel";
            public const string SpeakLevel = "s_SpeakLevel";
            public const string Points = "s_Points";

		}
		#endregion		
		
		#region Properties
	
		public virtual int RowID
	    {
			get
	        {
				return base.Getint(ColumnNames.RowID);
			}
			set
	        {
				base.Setint(ColumnNames.RowID, value);
			}
		}

		public virtual int JobID
	    {
			get
	        {
				return base.Getint(ColumnNames.JobID);
			}
			set
	        {
				base.Setint(ColumnNames.JobID, value);
			}
		}

		public virtual int ForeignLanguageID
	    {
			get
	        {
				return base.Getint(ColumnNames.ForeignLanguageID);
			}
			set
	        {
				base.Setint(ColumnNames.ForeignLanguageID, value);
			}
		}

		public virtual int ReadLevel
	    {
			get
	        {
				return base.Getint(ColumnNames.ReadLevel);
			}
			set
	        {
				base.Setint(ColumnNames.ReadLevel, value);
			}
		}

		public virtual int WriteLevel
	    {
			get
	        {
				return base.Getint(ColumnNames.WriteLevel);
			}
			set
	        {
				base.Setint(ColumnNames.WriteLevel, value);
			}
		}

		public virtual int SpeakLevel
	    {
			get
	        {
				return base.Getint(ColumnNames.SpeakLevel);
			}
			set
	        {
				base.Setint(ColumnNames.SpeakLevel, value);
			}
		}

		public virtual int Points
	    {
			get
	        {
				return base.Getint(ColumnNames.Points);
			}
			set
	        {
				base.Setint(ColumnNames.Points, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_RowID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RowID) ? string.Empty : base.GetintAsString(ColumnNames.RowID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RowID);
				else
					this.RowID = base.SetintAsString(ColumnNames.RowID, value);
			}
		}

		public virtual string s_JobID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.JobID) ? string.Empty : base.GetintAsString(ColumnNames.JobID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.JobID);
				else
					this.JobID = base.SetintAsString(ColumnNames.JobID, value);
			}
		}

		public virtual string s_ForeignLanguageID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ForeignLanguageID) ? string.Empty : base.GetintAsString(ColumnNames.ForeignLanguageID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ForeignLanguageID);
				else
					this.ForeignLanguageID = base.SetintAsString(ColumnNames.ForeignLanguageID, value);
			}
		}

		public virtual string s_ReadLevel
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ReadLevel) ? string.Empty : base.GetintAsString(ColumnNames.ReadLevel);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ReadLevel);
				else
					this.ReadLevel = base.SetintAsString(ColumnNames.ReadLevel, value);
			}
		}

		public virtual string s_WriteLevel
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.WriteLevel) ? string.Empty : base.GetintAsString(ColumnNames.WriteLevel);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.WriteLevel);
				else
					this.WriteLevel = base.SetintAsString(ColumnNames.WriteLevel, value);
			}
		}

		public virtual string s_SpeakLevel
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SpeakLevel) ? string.Empty : base.GetintAsString(ColumnNames.SpeakLevel);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SpeakLevel);
				else
					this.SpeakLevel = base.SetintAsString(ColumnNames.SpeakLevel, value);
			}
		}

		public virtual string s_Points
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Points) ? string.Empty : base.GetintAsString(ColumnNames.Points);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Points);
				else
					this.Points = base.SetintAsString(ColumnNames.Points, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter RowID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RowID, Parameters.RowID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter JobID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.JobID, Parameters.JobID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ForeignLanguageID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ForeignLanguageID, Parameters.ForeignLanguageID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ReadLevel
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ReadLevel, Parameters.ReadLevel);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter WriteLevel
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.WriteLevel, Parameters.WriteLevel);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SpeakLevel
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SpeakLevel, Parameters.SpeakLevel);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Points
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Points, Parameters.Points);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter RowID
		    {
				get
		        {
					if(_RowID_W == null)
	        	    {
						_RowID_W = TearOff.RowID;
					}
					return _RowID_W;
				}
			}

			public WhereParameter JobID
		    {
				get
		        {
					if(_JobID_W == null)
	        	    {
						_JobID_W = TearOff.JobID;
					}
					return _JobID_W;
				}
			}

			public WhereParameter ForeignLanguageID
		    {
				get
		        {
					if(_ForeignLanguageID_W == null)
	        	    {
						_ForeignLanguageID_W = TearOff.ForeignLanguageID;
					}
					return _ForeignLanguageID_W;
				}
			}

			public WhereParameter ReadLevel
		    {
				get
		        {
					if(_ReadLevel_W == null)
	        	    {
						_ReadLevel_W = TearOff.ReadLevel;
					}
					return _ReadLevel_W;
				}
			}

			public WhereParameter WriteLevel
		    {
				get
		        {
					if(_WriteLevel_W == null)
	        	    {
						_WriteLevel_W = TearOff.WriteLevel;
					}
					return _WriteLevel_W;
				}
			}

			public WhereParameter SpeakLevel
		    {
				get
		        {
					if(_SpeakLevel_W == null)
	        	    {
						_SpeakLevel_W = TearOff.SpeakLevel;
					}
					return _SpeakLevel_W;
				}
			}

			public WhereParameter Points
		    {
				get
		        {
					if(_Points_W == null)
	        	    {
						_Points_W = TearOff.Points;
					}
					return _Points_W;
				}
			}

			private WhereParameter _RowID_W = null;
			private WhereParameter _JobID_W = null;
			private WhereParameter _ForeignLanguageID_W = null;
			private WhereParameter _ReadLevel_W = null;
			private WhereParameter _WriteLevel_W = null;
			private WhereParameter _SpeakLevel_W = null;
			private WhereParameter _Points_W = null;

			public void WhereClauseReset()
			{
				_RowID_W = null;
				_JobID_W = null;
				_ForeignLanguageID_W = null;
				_ReadLevel_W = null;
				_WriteLevel_W = null;
				_SpeakLevel_W = null;
				_Points_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter RowID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RowID, Parameters.RowID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter JobID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.JobID, Parameters.JobID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ForeignLanguageID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ForeignLanguageID, Parameters.ForeignLanguageID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ReadLevel
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ReadLevel, Parameters.ReadLevel);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter WriteLevel
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.WriteLevel, Parameters.WriteLevel);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SpeakLevel
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SpeakLevel, Parameters.SpeakLevel);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Points
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Points, Parameters.Points);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter RowID
		    {
				get
		        {
					if(_RowID_W == null)
	        	    {
						_RowID_W = TearOff.RowID;
					}
					return _RowID_W;
				}
			}

			public AggregateParameter JobID
		    {
				get
		        {
					if(_JobID_W == null)
	        	    {
						_JobID_W = TearOff.JobID;
					}
					return _JobID_W;
				}
			}

			public AggregateParameter ForeignLanguageID
		    {
				get
		        {
					if(_ForeignLanguageID_W == null)
	        	    {
						_ForeignLanguageID_W = TearOff.ForeignLanguageID;
					}
					return _ForeignLanguageID_W;
				}
			}

			public AggregateParameter ReadLevel
		    {
				get
		        {
					if(_ReadLevel_W == null)
	        	    {
						_ReadLevel_W = TearOff.ReadLevel;
					}
					return _ReadLevel_W;
				}
			}

			public AggregateParameter WriteLevel
		    {
				get
		        {
					if(_WriteLevel_W == null)
	        	    {
						_WriteLevel_W = TearOff.WriteLevel;
					}
					return _WriteLevel_W;
				}
			}

			public AggregateParameter SpeakLevel
		    {
				get
		        {
					if(_SpeakLevel_W == null)
	        	    {
						_SpeakLevel_W = TearOff.SpeakLevel;
					}
					return _SpeakLevel_W;
				}
			}

			public AggregateParameter Points
		    {
				get
		        {
					if(_Points_W == null)
	        	    {
						_Points_W = TearOff.Points;
					}
					return _Points_W;
				}
			}

			private AggregateParameter _RowID_W = null;
			private AggregateParameter _JobID_W = null;
			private AggregateParameter _ForeignLanguageID_W = null;
			private AggregateParameter _ReadLevel_W = null;
			private AggregateParameter _WriteLevel_W = null;
			private AggregateParameter _SpeakLevel_W = null;
			private AggregateParameter _Points_W = null;

			public void AggregateClauseReset()
			{
				_RowID_W = null;
				_JobID_W = null;
				_ForeignLanguageID_W = null;
				_ReadLevel_W = null;
				_WriteLevel_W = null;
				_SpeakLevel_W = null;
				_Points_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobChoiceForeignLanguageInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.RowID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobChoiceForeignLanguageUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobChoiceForeignLanguageDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.RowID);
			p.SourceColumn = ColumnNames.RowID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.RowID);
			p.SourceColumn = ColumnNames.RowID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.JobID);
			p.SourceColumn = ColumnNames.JobID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ForeignLanguageID);
			p.SourceColumn = ColumnNames.ForeignLanguageID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ReadLevel);
			p.SourceColumn = ColumnNames.ReadLevel;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.WriteLevel);
			p.SourceColumn = ColumnNames.WriteLevel;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SpeakLevel);
			p.SourceColumn = ColumnNames.SpeakLevel;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Points);
			p.SourceColumn = ColumnNames.Points;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
