
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _JobApplicationStatusChanges : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _JobApplicationStatusChanges()
		{
			this.QuerySource = "JobApplicationStatusChanges";
			this.MappingName = "JobApplicationStatusChanges";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_JobApplicationStatusChangesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int JobApplicationStatusChangeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.JobApplicationStatusChangeID, JobApplicationStatusChangeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_JobApplicationStatusChangesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter JobApplicationStatusChangeID
			{
				get
				{
					return new SqlParameter("@JobApplicationStatusChangeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter JobApplicantID
			{
				get
				{
					return new SqlParameter("@JobApplicantID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ApplicationDate
			{
				get
				{
					return new SqlParameter("@ApplicationDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ApplicationStatusID
			{
				get
				{
					return new SqlParameter("@ApplicationStatusID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ApplicationTitle
			{
				get
				{
					return new SqlParameter("@ApplicationTitle", SqlDbType.NVarChar, 128);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string JobApplicationStatusChangeID = "JobApplicationStatusChangeID";
            public const string JobApplicantID = "JobApplicantID";
            public const string ApplicationDate = "ApplicationDate";
            public const string ApplicationStatusID = "ApplicationStatusID";
            public const string ApplicationTitle = "ApplicationTitle";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[JobApplicationStatusChangeID] = _JobApplicationStatusChanges.PropertyNames.JobApplicationStatusChangeID;
					ht[JobApplicantID] = _JobApplicationStatusChanges.PropertyNames.JobApplicantID;
					ht[ApplicationDate] = _JobApplicationStatusChanges.PropertyNames.ApplicationDate;
					ht[ApplicationStatusID] = _JobApplicationStatusChanges.PropertyNames.ApplicationStatusID;
					ht[ApplicationTitle] = _JobApplicationStatusChanges.PropertyNames.ApplicationTitle;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string JobApplicationStatusChangeID = "JobApplicationStatusChangeID";
            public const string JobApplicantID = "JobApplicantID";
            public const string ApplicationDate = "ApplicationDate";
            public const string ApplicationStatusID = "ApplicationStatusID";
            public const string ApplicationTitle = "ApplicationTitle";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[JobApplicationStatusChangeID] = _JobApplicationStatusChanges.ColumnNames.JobApplicationStatusChangeID;
					ht[JobApplicantID] = _JobApplicationStatusChanges.ColumnNames.JobApplicantID;
					ht[ApplicationDate] = _JobApplicationStatusChanges.ColumnNames.ApplicationDate;
					ht[ApplicationStatusID] = _JobApplicationStatusChanges.ColumnNames.ApplicationStatusID;
					ht[ApplicationTitle] = _JobApplicationStatusChanges.ColumnNames.ApplicationTitle;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string JobApplicationStatusChangeID = "s_JobApplicationStatusChangeID";
            public const string JobApplicantID = "s_JobApplicantID";
            public const string ApplicationDate = "s_ApplicationDate";
            public const string ApplicationStatusID = "s_ApplicationStatusID";
            public const string ApplicationTitle = "s_ApplicationTitle";

		}
		#endregion		
		
		#region Properties
	
		public virtual int JobApplicationStatusChangeID
	    {
			get
	        {
				return base.Getint(ColumnNames.JobApplicationStatusChangeID);
			}
			set
	        {
				base.Setint(ColumnNames.JobApplicationStatusChangeID, value);
			}
		}

		public virtual int JobApplicantID
	    {
			get
	        {
				return base.Getint(ColumnNames.JobApplicantID);
			}
			set
	        {
				base.Setint(ColumnNames.JobApplicantID, value);
			}
		}

		public virtual DateTime ApplicationDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ApplicationDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ApplicationDate, value);
			}
		}

		public virtual int ApplicationStatusID
	    {
			get
	        {
				return base.Getint(ColumnNames.ApplicationStatusID);
			}
			set
	        {
				base.Setint(ColumnNames.ApplicationStatusID, value);
			}
		}

		public virtual string ApplicationTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.ApplicationTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.ApplicationTitle, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_JobApplicationStatusChangeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.JobApplicationStatusChangeID) ? string.Empty : base.GetintAsString(ColumnNames.JobApplicationStatusChangeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.JobApplicationStatusChangeID);
				else
					this.JobApplicationStatusChangeID = base.SetintAsString(ColumnNames.JobApplicationStatusChangeID, value);
			}
		}

		public virtual string s_JobApplicantID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.JobApplicantID) ? string.Empty : base.GetintAsString(ColumnNames.JobApplicantID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.JobApplicantID);
				else
					this.JobApplicantID = base.SetintAsString(ColumnNames.JobApplicantID, value);
			}
		}

		public virtual string s_ApplicationDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ApplicationDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ApplicationDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ApplicationDate);
				else
					this.ApplicationDate = base.SetDateTimeAsString(ColumnNames.ApplicationDate, value);
			}
		}

		public virtual string s_ApplicationStatusID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ApplicationStatusID) ? string.Empty : base.GetintAsString(ColumnNames.ApplicationStatusID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ApplicationStatusID);
				else
					this.ApplicationStatusID = base.SetintAsString(ColumnNames.ApplicationStatusID, value);
			}
		}

		public virtual string s_ApplicationTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ApplicationTitle) ? string.Empty : base.GetstringAsString(ColumnNames.ApplicationTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ApplicationTitle);
				else
					this.ApplicationTitle = base.SetstringAsString(ColumnNames.ApplicationTitle, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter JobApplicationStatusChangeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.JobApplicationStatusChangeID, Parameters.JobApplicationStatusChangeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter JobApplicantID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.JobApplicantID, Parameters.JobApplicantID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ApplicationDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ApplicationDate, Parameters.ApplicationDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ApplicationStatusID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ApplicationStatusID, Parameters.ApplicationStatusID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ApplicationTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ApplicationTitle, Parameters.ApplicationTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter JobApplicationStatusChangeID
		    {
				get
		        {
					if(_JobApplicationStatusChangeID_W == null)
	        	    {
						_JobApplicationStatusChangeID_W = TearOff.JobApplicationStatusChangeID;
					}
					return _JobApplicationStatusChangeID_W;
				}
			}

			public WhereParameter JobApplicantID
		    {
				get
		        {
					if(_JobApplicantID_W == null)
	        	    {
						_JobApplicantID_W = TearOff.JobApplicantID;
					}
					return _JobApplicantID_W;
				}
			}

			public WhereParameter ApplicationDate
		    {
				get
		        {
					if(_ApplicationDate_W == null)
	        	    {
						_ApplicationDate_W = TearOff.ApplicationDate;
					}
					return _ApplicationDate_W;
				}
			}

			public WhereParameter ApplicationStatusID
		    {
				get
		        {
					if(_ApplicationStatusID_W == null)
	        	    {
						_ApplicationStatusID_W = TearOff.ApplicationStatusID;
					}
					return _ApplicationStatusID_W;
				}
			}

			public WhereParameter ApplicationTitle
		    {
				get
		        {
					if(_ApplicationTitle_W == null)
	        	    {
						_ApplicationTitle_W = TearOff.ApplicationTitle;
					}
					return _ApplicationTitle_W;
				}
			}

			private WhereParameter _JobApplicationStatusChangeID_W = null;
			private WhereParameter _JobApplicantID_W = null;
			private WhereParameter _ApplicationDate_W = null;
			private WhereParameter _ApplicationStatusID_W = null;
			private WhereParameter _ApplicationTitle_W = null;

			public void WhereClauseReset()
			{
				_JobApplicationStatusChangeID_W = null;
				_JobApplicantID_W = null;
				_ApplicationDate_W = null;
				_ApplicationStatusID_W = null;
				_ApplicationTitle_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter JobApplicationStatusChangeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.JobApplicationStatusChangeID, Parameters.JobApplicationStatusChangeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter JobApplicantID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.JobApplicantID, Parameters.JobApplicantID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ApplicationDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ApplicationDate, Parameters.ApplicationDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ApplicationStatusID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ApplicationStatusID, Parameters.ApplicationStatusID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ApplicationTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ApplicationTitle, Parameters.ApplicationTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter JobApplicationStatusChangeID
		    {
				get
		        {
					if(_JobApplicationStatusChangeID_W == null)
	        	    {
						_JobApplicationStatusChangeID_W = TearOff.JobApplicationStatusChangeID;
					}
					return _JobApplicationStatusChangeID_W;
				}
			}

			public AggregateParameter JobApplicantID
		    {
				get
		        {
					if(_JobApplicantID_W == null)
	        	    {
						_JobApplicantID_W = TearOff.JobApplicantID;
					}
					return _JobApplicantID_W;
				}
			}

			public AggregateParameter ApplicationDate
		    {
				get
		        {
					if(_ApplicationDate_W == null)
	        	    {
						_ApplicationDate_W = TearOff.ApplicationDate;
					}
					return _ApplicationDate_W;
				}
			}

			public AggregateParameter ApplicationStatusID
		    {
				get
		        {
					if(_ApplicationStatusID_W == null)
	        	    {
						_ApplicationStatusID_W = TearOff.ApplicationStatusID;
					}
					return _ApplicationStatusID_W;
				}
			}

			public AggregateParameter ApplicationTitle
		    {
				get
		        {
					if(_ApplicationTitle_W == null)
	        	    {
						_ApplicationTitle_W = TearOff.ApplicationTitle;
					}
					return _ApplicationTitle_W;
				}
			}

			private AggregateParameter _JobApplicationStatusChangeID_W = null;
			private AggregateParameter _JobApplicantID_W = null;
			private AggregateParameter _ApplicationDate_W = null;
			private AggregateParameter _ApplicationStatusID_W = null;
			private AggregateParameter _ApplicationTitle_W = null;

			public void AggregateClauseReset()
			{
				_JobApplicationStatusChangeID_W = null;
				_JobApplicantID_W = null;
				_ApplicationDate_W = null;
				_ApplicationStatusID_W = null;
				_ApplicationTitle_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobApplicationStatusChangesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.JobApplicationStatusChangeID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobApplicationStatusChangesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_JobApplicationStatusChangesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.JobApplicationStatusChangeID);
			p.SourceColumn = ColumnNames.JobApplicationStatusChangeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.JobApplicationStatusChangeID);
			p.SourceColumn = ColumnNames.JobApplicationStatusChangeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.JobApplicantID);
			p.SourceColumn = ColumnNames.JobApplicantID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ApplicationDate);
			p.SourceColumn = ColumnNames.ApplicationDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ApplicationStatusID);
			p.SourceColumn = ColumnNames.ApplicationStatusID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ApplicationTitle);
			p.SourceColumn = ColumnNames.ApplicationTitle;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
