
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _OrderTypes : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _OrderTypes()
		{
			this.QuerySource = "OrderTypes";
			this.MappingName = "OrderTypes";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_OrderTypesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int OrderTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.OrderTypeID, OrderTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_OrderTypesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter OrderTypeID
			{
				get
				{
					return new SqlParameter("@OrderTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PikPoolCredit
			{
				get
				{
					return new SqlParameter("@PikPoolCredit", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter GoodPikCredit
			{
				get
				{
					return new SqlParameter("@GoodPikCredit", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IsDeleted
			{
				get
				{
					return new SqlParameter("@IsDeleted", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string OrderTypeID = "OrderTypeID";
            public const string PikPoolCredit = "PikPoolCredit";
            public const string GoodPikCredit = "GoodPikCredit";
            public const string IsDeleted = "IsDeleted";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[OrderTypeID] = _OrderTypes.PropertyNames.OrderTypeID;
					ht[PikPoolCredit] = _OrderTypes.PropertyNames.PikPoolCredit;
					ht[GoodPikCredit] = _OrderTypes.PropertyNames.GoodPikCredit;
					ht[IsDeleted] = _OrderTypes.PropertyNames.IsDeleted;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string OrderTypeID = "OrderTypeID";
            public const string PikPoolCredit = "PikPoolCredit";
            public const string GoodPikCredit = "GoodPikCredit";
            public const string IsDeleted = "IsDeleted";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[OrderTypeID] = _OrderTypes.ColumnNames.OrderTypeID;
					ht[PikPoolCredit] = _OrderTypes.ColumnNames.PikPoolCredit;
					ht[GoodPikCredit] = _OrderTypes.ColumnNames.GoodPikCredit;
					ht[IsDeleted] = _OrderTypes.ColumnNames.IsDeleted;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string OrderTypeID = "s_OrderTypeID";
            public const string PikPoolCredit = "s_PikPoolCredit";
            public const string GoodPikCredit = "s_GoodPikCredit";
            public const string IsDeleted = "s_IsDeleted";

		}
		#endregion		
		
		#region Properties
	
		public virtual int OrderTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.OrderTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.OrderTypeID, value);
			}
		}

		public virtual int PikPoolCredit
	    {
			get
	        {
				return base.Getint(ColumnNames.PikPoolCredit);
			}
			set
	        {
				base.Setint(ColumnNames.PikPoolCredit, value);
			}
		}

		public virtual int GoodPikCredit
	    {
			get
	        {
				return base.Getint(ColumnNames.GoodPikCredit);
			}
			set
	        {
				base.Setint(ColumnNames.GoodPikCredit, value);
			}
		}

		public virtual bool IsDeleted
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsDeleted);
			}
			set
	        {
				base.Setbool(ColumnNames.IsDeleted, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_OrderTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.OrderTypeID) ? string.Empty : base.GetintAsString(ColumnNames.OrderTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.OrderTypeID);
				else
					this.OrderTypeID = base.SetintAsString(ColumnNames.OrderTypeID, value);
			}
		}

		public virtual string s_PikPoolCredit
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PikPoolCredit) ? string.Empty : base.GetintAsString(ColumnNames.PikPoolCredit);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PikPoolCredit);
				else
					this.PikPoolCredit = base.SetintAsString(ColumnNames.PikPoolCredit, value);
			}
		}

		public virtual string s_GoodPikCredit
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GoodPikCredit) ? string.Empty : base.GetintAsString(ColumnNames.GoodPikCredit);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GoodPikCredit);
				else
					this.GoodPikCredit = base.SetintAsString(ColumnNames.GoodPikCredit, value);
			}
		}

		public virtual string s_IsDeleted
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsDeleted) ? string.Empty : base.GetboolAsString(ColumnNames.IsDeleted);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsDeleted);
				else
					this.IsDeleted = base.SetboolAsString(ColumnNames.IsDeleted, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter OrderTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.OrderTypeID, Parameters.OrderTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PikPoolCredit
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PikPoolCredit, Parameters.PikPoolCredit);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GoodPikCredit
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GoodPikCredit, Parameters.GoodPikCredit);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsDeleted
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsDeleted, Parameters.IsDeleted);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter OrderTypeID
		    {
				get
		        {
					if(_OrderTypeID_W == null)
	        	    {
						_OrderTypeID_W = TearOff.OrderTypeID;
					}
					return _OrderTypeID_W;
				}
			}

			public WhereParameter PikPoolCredit
		    {
				get
		        {
					if(_PikPoolCredit_W == null)
	        	    {
						_PikPoolCredit_W = TearOff.PikPoolCredit;
					}
					return _PikPoolCredit_W;
				}
			}

			public WhereParameter GoodPikCredit
		    {
				get
		        {
					if(_GoodPikCredit_W == null)
	        	    {
						_GoodPikCredit_W = TearOff.GoodPikCredit;
					}
					return _GoodPikCredit_W;
				}
			}

			public WhereParameter IsDeleted
		    {
				get
		        {
					if(_IsDeleted_W == null)
	        	    {
						_IsDeleted_W = TearOff.IsDeleted;
					}
					return _IsDeleted_W;
				}
			}

			private WhereParameter _OrderTypeID_W = null;
			private WhereParameter _PikPoolCredit_W = null;
			private WhereParameter _GoodPikCredit_W = null;
			private WhereParameter _IsDeleted_W = null;

			public void WhereClauseReset()
			{
				_OrderTypeID_W = null;
				_PikPoolCredit_W = null;
				_GoodPikCredit_W = null;
				_IsDeleted_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter OrderTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.OrderTypeID, Parameters.OrderTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PikPoolCredit
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PikPoolCredit, Parameters.PikPoolCredit);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GoodPikCredit
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GoodPikCredit, Parameters.GoodPikCredit);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsDeleted
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsDeleted, Parameters.IsDeleted);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter OrderTypeID
		    {
				get
		        {
					if(_OrderTypeID_W == null)
	        	    {
						_OrderTypeID_W = TearOff.OrderTypeID;
					}
					return _OrderTypeID_W;
				}
			}

			public AggregateParameter PikPoolCredit
		    {
				get
		        {
					if(_PikPoolCredit_W == null)
	        	    {
						_PikPoolCredit_W = TearOff.PikPoolCredit;
					}
					return _PikPoolCredit_W;
				}
			}

			public AggregateParameter GoodPikCredit
		    {
				get
		        {
					if(_GoodPikCredit_W == null)
	        	    {
						_GoodPikCredit_W = TearOff.GoodPikCredit;
					}
					return _GoodPikCredit_W;
				}
			}

			public AggregateParameter IsDeleted
		    {
				get
		        {
					if(_IsDeleted_W == null)
	        	    {
						_IsDeleted_W = TearOff.IsDeleted;
					}
					return _IsDeleted_W;
				}
			}

			private AggregateParameter _OrderTypeID_W = null;
			private AggregateParameter _PikPoolCredit_W = null;
			private AggregateParameter _GoodPikCredit_W = null;
			private AggregateParameter _IsDeleted_W = null;

			public void AggregateClauseReset()
			{
				_OrderTypeID_W = null;
				_PikPoolCredit_W = null;
				_GoodPikCredit_W = null;
				_IsDeleted_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrderTypesInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrderTypesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrderTypesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.OrderTypeID);
			p.SourceColumn = ColumnNames.OrderTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.OrderTypeID);
			p.SourceColumn = ColumnNames.OrderTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PikPoolCredit);
			p.SourceColumn = ColumnNames.PikPoolCredit;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GoodPikCredit);
			p.SourceColumn = ColumnNames.GoodPikCredit;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsDeleted);
			p.SourceColumn = ColumnNames.IsDeleted;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
