
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _Representatives : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _Representatives()
		{
			this.QuerySource = "Representatives";
			this.MappingName = "Representatives";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RepresentativesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int RepresentativeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.RepresentativeID, RepresentativeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RepresentativesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter RepresentativeID
			{
				get
				{
					return new SqlParameter("@RepresentativeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter RepresentativeName
			{
				get
				{
					return new SqlParameter("@RepresentativeName", SqlDbType.NVarChar, 32);
				}
			}
			
			public static SqlParameter RepresentativeLastName
			{
				get
				{
					return new SqlParameter("@RepresentativeLastName", SqlDbType.NVarChar, 32);
				}
			}
			
			public static SqlParameter RepresentativeEmail
			{
				get
				{
					return new SqlParameter("@RepresentativeEmail", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter RepresentativePhone
			{
				get
				{
					return new SqlParameter("@RepresentativePhone", SqlDbType.VarChar, 24);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string RepresentativeID = "RepresentativeID";
            public const string RepresentativeName = "RepresentativeName";
            public const string RepresentativeLastName = "RepresentativeLastName";
            public const string RepresentativeEmail = "RepresentativeEmail";
            public const string RepresentativePhone = "RepresentativePhone";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RepresentativeID] = _Representatives.PropertyNames.RepresentativeID;
					ht[RepresentativeName] = _Representatives.PropertyNames.RepresentativeName;
					ht[RepresentativeLastName] = _Representatives.PropertyNames.RepresentativeLastName;
					ht[RepresentativeEmail] = _Representatives.PropertyNames.RepresentativeEmail;
					ht[RepresentativePhone] = _Representatives.PropertyNames.RepresentativePhone;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string RepresentativeID = "RepresentativeID";
            public const string RepresentativeName = "RepresentativeName";
            public const string RepresentativeLastName = "RepresentativeLastName";
            public const string RepresentativeEmail = "RepresentativeEmail";
            public const string RepresentativePhone = "RepresentativePhone";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RepresentativeID] = _Representatives.ColumnNames.RepresentativeID;
					ht[RepresentativeName] = _Representatives.ColumnNames.RepresentativeName;
					ht[RepresentativeLastName] = _Representatives.ColumnNames.RepresentativeLastName;
					ht[RepresentativeEmail] = _Representatives.ColumnNames.RepresentativeEmail;
					ht[RepresentativePhone] = _Representatives.ColumnNames.RepresentativePhone;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string RepresentativeID = "s_RepresentativeID";
            public const string RepresentativeName = "s_RepresentativeName";
            public const string RepresentativeLastName = "s_RepresentativeLastName";
            public const string RepresentativeEmail = "s_RepresentativeEmail";
            public const string RepresentativePhone = "s_RepresentativePhone";

		}
		#endregion		
		
		#region Properties
	
		public virtual int RepresentativeID
	    {
			get
	        {
				return base.Getint(ColumnNames.RepresentativeID);
			}
			set
	        {
				base.Setint(ColumnNames.RepresentativeID, value);
			}
		}

		public virtual string RepresentativeName
	    {
			get
	        {
				return base.Getstring(ColumnNames.RepresentativeName);
			}
			set
	        {
				base.Setstring(ColumnNames.RepresentativeName, value);
			}
		}

		public virtual string RepresentativeLastName
	    {
			get
	        {
				return base.Getstring(ColumnNames.RepresentativeLastName);
			}
			set
	        {
				base.Setstring(ColumnNames.RepresentativeLastName, value);
			}
		}

		public virtual string RepresentativeEmail
	    {
			get
	        {
				return base.Getstring(ColumnNames.RepresentativeEmail);
			}
			set
	        {
				base.Setstring(ColumnNames.RepresentativeEmail, value);
			}
		}

		public virtual string RepresentativePhone
	    {
			get
	        {
				return base.Getstring(ColumnNames.RepresentativePhone);
			}
			set
	        {
				base.Setstring(ColumnNames.RepresentativePhone, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_RepresentativeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RepresentativeID) ? string.Empty : base.GetintAsString(ColumnNames.RepresentativeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RepresentativeID);
				else
					this.RepresentativeID = base.SetintAsString(ColumnNames.RepresentativeID, value);
			}
		}

		public virtual string s_RepresentativeName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RepresentativeName) ? string.Empty : base.GetstringAsString(ColumnNames.RepresentativeName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RepresentativeName);
				else
					this.RepresentativeName = base.SetstringAsString(ColumnNames.RepresentativeName, value);
			}
		}

		public virtual string s_RepresentativeLastName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RepresentativeLastName) ? string.Empty : base.GetstringAsString(ColumnNames.RepresentativeLastName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RepresentativeLastName);
				else
					this.RepresentativeLastName = base.SetstringAsString(ColumnNames.RepresentativeLastName, value);
			}
		}

		public virtual string s_RepresentativeEmail
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RepresentativeEmail) ? string.Empty : base.GetstringAsString(ColumnNames.RepresentativeEmail);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RepresentativeEmail);
				else
					this.RepresentativeEmail = base.SetstringAsString(ColumnNames.RepresentativeEmail, value);
			}
		}

		public virtual string s_RepresentativePhone
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RepresentativePhone) ? string.Empty : base.GetstringAsString(ColumnNames.RepresentativePhone);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RepresentativePhone);
				else
					this.RepresentativePhone = base.SetstringAsString(ColumnNames.RepresentativePhone, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter RepresentativeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RepresentativeID, Parameters.RepresentativeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RepresentativeName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RepresentativeName, Parameters.RepresentativeName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RepresentativeLastName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RepresentativeLastName, Parameters.RepresentativeLastName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RepresentativeEmail
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RepresentativeEmail, Parameters.RepresentativeEmail);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RepresentativePhone
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RepresentativePhone, Parameters.RepresentativePhone);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter RepresentativeID
		    {
				get
		        {
					if(_RepresentativeID_W == null)
	        	    {
						_RepresentativeID_W = TearOff.RepresentativeID;
					}
					return _RepresentativeID_W;
				}
			}

			public WhereParameter RepresentativeName
		    {
				get
		        {
					if(_RepresentativeName_W == null)
	        	    {
						_RepresentativeName_W = TearOff.RepresentativeName;
					}
					return _RepresentativeName_W;
				}
			}

			public WhereParameter RepresentativeLastName
		    {
				get
		        {
					if(_RepresentativeLastName_W == null)
	        	    {
						_RepresentativeLastName_W = TearOff.RepresentativeLastName;
					}
					return _RepresentativeLastName_W;
				}
			}

			public WhereParameter RepresentativeEmail
		    {
				get
		        {
					if(_RepresentativeEmail_W == null)
	        	    {
						_RepresentativeEmail_W = TearOff.RepresentativeEmail;
					}
					return _RepresentativeEmail_W;
				}
			}

			public WhereParameter RepresentativePhone
		    {
				get
		        {
					if(_RepresentativePhone_W == null)
	        	    {
						_RepresentativePhone_W = TearOff.RepresentativePhone;
					}
					return _RepresentativePhone_W;
				}
			}

			private WhereParameter _RepresentativeID_W = null;
			private WhereParameter _RepresentativeName_W = null;
			private WhereParameter _RepresentativeLastName_W = null;
			private WhereParameter _RepresentativeEmail_W = null;
			private WhereParameter _RepresentativePhone_W = null;

			public void WhereClauseReset()
			{
				_RepresentativeID_W = null;
				_RepresentativeName_W = null;
				_RepresentativeLastName_W = null;
				_RepresentativeEmail_W = null;
				_RepresentativePhone_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter RepresentativeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RepresentativeID, Parameters.RepresentativeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RepresentativeName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RepresentativeName, Parameters.RepresentativeName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RepresentativeLastName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RepresentativeLastName, Parameters.RepresentativeLastName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RepresentativeEmail
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RepresentativeEmail, Parameters.RepresentativeEmail);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RepresentativePhone
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RepresentativePhone, Parameters.RepresentativePhone);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter RepresentativeID
		    {
				get
		        {
					if(_RepresentativeID_W == null)
	        	    {
						_RepresentativeID_W = TearOff.RepresentativeID;
					}
					return _RepresentativeID_W;
				}
			}

			public AggregateParameter RepresentativeName
		    {
				get
		        {
					if(_RepresentativeName_W == null)
	        	    {
						_RepresentativeName_W = TearOff.RepresentativeName;
					}
					return _RepresentativeName_W;
				}
			}

			public AggregateParameter RepresentativeLastName
		    {
				get
		        {
					if(_RepresentativeLastName_W == null)
	        	    {
						_RepresentativeLastName_W = TearOff.RepresentativeLastName;
					}
					return _RepresentativeLastName_W;
				}
			}

			public AggregateParameter RepresentativeEmail
		    {
				get
		        {
					if(_RepresentativeEmail_W == null)
	        	    {
						_RepresentativeEmail_W = TearOff.RepresentativeEmail;
					}
					return _RepresentativeEmail_W;
				}
			}

			public AggregateParameter RepresentativePhone
		    {
				get
		        {
					if(_RepresentativePhone_W == null)
	        	    {
						_RepresentativePhone_W = TearOff.RepresentativePhone;
					}
					return _RepresentativePhone_W;
				}
			}

			private AggregateParameter _RepresentativeID_W = null;
			private AggregateParameter _RepresentativeName_W = null;
			private AggregateParameter _RepresentativeLastName_W = null;
			private AggregateParameter _RepresentativeEmail_W = null;
			private AggregateParameter _RepresentativePhone_W = null;

			public void AggregateClauseReset()
			{
				_RepresentativeID_W = null;
				_RepresentativeName_W = null;
				_RepresentativeLastName_W = null;
				_RepresentativeEmail_W = null;
				_RepresentativePhone_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RepresentativesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.RepresentativeID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RepresentativesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RepresentativesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.RepresentativeID);
			p.SourceColumn = ColumnNames.RepresentativeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.RepresentativeID);
			p.SourceColumn = ColumnNames.RepresentativeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RepresentativeName);
			p.SourceColumn = ColumnNames.RepresentativeName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RepresentativeLastName);
			p.SourceColumn = ColumnNames.RepresentativeLastName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RepresentativeEmail);
			p.SourceColumn = ColumnNames.RepresentativeEmail;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RepresentativePhone);
			p.SourceColumn = ColumnNames.RepresentativePhone;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
