
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _SystemUserRoles : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _SystemUserRoles()
		{
			this.QuerySource = "SystemUserRoles";
			this.MappingName = "SystemUserRoles";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SystemUserRolesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SystemUserRoleID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SystemUserRoleID, SystemUserRoleID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SystemUserRolesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SystemUserRoleID
			{
				get
				{
					return new SqlParameter("@SystemUserRoleID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SystemUserID
			{
				get
				{
					return new SqlParameter("@SystemUserID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SystetRoleID
			{
				get
				{
					return new SqlParameter("@SystetRoleID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ModifyDate
			{
				get
				{
					return new SqlParameter("@ModifyDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SystemUserRoleID = "SystemUserRoleID";
            public const string SystemUserID = "SystemUserID";
            public const string SystetRoleID = "SystetRoleID";
            public const string ModifyDate = "ModifyDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SystemUserRoleID] = _SystemUserRoles.PropertyNames.SystemUserRoleID;
					ht[SystemUserID] = _SystemUserRoles.PropertyNames.SystemUserID;
					ht[SystetRoleID] = _SystemUserRoles.PropertyNames.SystetRoleID;
					ht[ModifyDate] = _SystemUserRoles.PropertyNames.ModifyDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SystemUserRoleID = "SystemUserRoleID";
            public const string SystemUserID = "SystemUserID";
            public const string SystetRoleID = "SystetRoleID";
            public const string ModifyDate = "ModifyDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SystemUserRoleID] = _SystemUserRoles.ColumnNames.SystemUserRoleID;
					ht[SystemUserID] = _SystemUserRoles.ColumnNames.SystemUserID;
					ht[SystetRoleID] = _SystemUserRoles.ColumnNames.SystetRoleID;
					ht[ModifyDate] = _SystemUserRoles.ColumnNames.ModifyDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SystemUserRoleID = "s_SystemUserRoleID";
            public const string SystemUserID = "s_SystemUserID";
            public const string SystetRoleID = "s_SystetRoleID";
            public const string ModifyDate = "s_ModifyDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int SystemUserRoleID
	    {
			get
	        {
				return base.Getint(ColumnNames.SystemUserRoleID);
			}
			set
	        {
				base.Setint(ColumnNames.SystemUserRoleID, value);
			}
		}

		public virtual int SystemUserID
	    {
			get
	        {
				return base.Getint(ColumnNames.SystemUserID);
			}
			set
	        {
				base.Setint(ColumnNames.SystemUserID, value);
			}
		}

		public virtual int SystetRoleID
	    {
			get
	        {
				return base.Getint(ColumnNames.SystetRoleID);
			}
			set
	        {
				base.Setint(ColumnNames.SystetRoleID, value);
			}
		}

		public virtual DateTime ModifyDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ModifyDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ModifyDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_SystemUserRoleID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SystemUserRoleID) ? string.Empty : base.GetintAsString(ColumnNames.SystemUserRoleID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SystemUserRoleID);
				else
					this.SystemUserRoleID = base.SetintAsString(ColumnNames.SystemUserRoleID, value);
			}
		}

		public virtual string s_SystemUserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SystemUserID) ? string.Empty : base.GetintAsString(ColumnNames.SystemUserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SystemUserID);
				else
					this.SystemUserID = base.SetintAsString(ColumnNames.SystemUserID, value);
			}
		}

		public virtual string s_SystetRoleID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SystetRoleID) ? string.Empty : base.GetintAsString(ColumnNames.SystetRoleID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SystetRoleID);
				else
					this.SystetRoleID = base.SetintAsString(ColumnNames.SystetRoleID, value);
			}
		}

		public virtual string s_ModifyDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifyDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ModifyDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifyDate);
				else
					this.ModifyDate = base.SetDateTimeAsString(ColumnNames.ModifyDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SystemUserRoleID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SystemUserRoleID, Parameters.SystemUserRoleID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SystemUserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SystemUserID, Parameters.SystemUserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SystetRoleID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SystetRoleID, Parameters.SystetRoleID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifyDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifyDate, Parameters.ModifyDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SystemUserRoleID
		    {
				get
		        {
					if(_SystemUserRoleID_W == null)
	        	    {
						_SystemUserRoleID_W = TearOff.SystemUserRoleID;
					}
					return _SystemUserRoleID_W;
				}
			}

			public WhereParameter SystemUserID
		    {
				get
		        {
					if(_SystemUserID_W == null)
	        	    {
						_SystemUserID_W = TearOff.SystemUserID;
					}
					return _SystemUserID_W;
				}
			}

			public WhereParameter SystetRoleID
		    {
				get
		        {
					if(_SystetRoleID_W == null)
	        	    {
						_SystetRoleID_W = TearOff.SystetRoleID;
					}
					return _SystetRoleID_W;
				}
			}

			public WhereParameter ModifyDate
		    {
				get
		        {
					if(_ModifyDate_W == null)
	        	    {
						_ModifyDate_W = TearOff.ModifyDate;
					}
					return _ModifyDate_W;
				}
			}

			private WhereParameter _SystemUserRoleID_W = null;
			private WhereParameter _SystemUserID_W = null;
			private WhereParameter _SystetRoleID_W = null;
			private WhereParameter _ModifyDate_W = null;

			public void WhereClauseReset()
			{
				_SystemUserRoleID_W = null;
				_SystemUserID_W = null;
				_SystetRoleID_W = null;
				_ModifyDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SystemUserRoleID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SystemUserRoleID, Parameters.SystemUserRoleID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SystemUserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SystemUserID, Parameters.SystemUserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SystetRoleID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SystetRoleID, Parameters.SystetRoleID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifyDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifyDate, Parameters.ModifyDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SystemUserRoleID
		    {
				get
		        {
					if(_SystemUserRoleID_W == null)
	        	    {
						_SystemUserRoleID_W = TearOff.SystemUserRoleID;
					}
					return _SystemUserRoleID_W;
				}
			}

			public AggregateParameter SystemUserID
		    {
				get
		        {
					if(_SystemUserID_W == null)
	        	    {
						_SystemUserID_W = TearOff.SystemUserID;
					}
					return _SystemUserID_W;
				}
			}

			public AggregateParameter SystetRoleID
		    {
				get
		        {
					if(_SystetRoleID_W == null)
	        	    {
						_SystetRoleID_W = TearOff.SystetRoleID;
					}
					return _SystetRoleID_W;
				}
			}

			public AggregateParameter ModifyDate
		    {
				get
		        {
					if(_ModifyDate_W == null)
	        	    {
						_ModifyDate_W = TearOff.ModifyDate;
					}
					return _ModifyDate_W;
				}
			}

			private AggregateParameter _SystemUserRoleID_W = null;
			private AggregateParameter _SystemUserID_W = null;
			private AggregateParameter _SystetRoleID_W = null;
			private AggregateParameter _ModifyDate_W = null;

			public void AggregateClauseReset()
			{
				_SystemUserRoleID_W = null;
				_SystemUserID_W = null;
				_SystetRoleID_W = null;
				_ModifyDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SystemUserRolesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.SystemUserRoleID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SystemUserRolesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SystemUserRolesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SystemUserRoleID);
			p.SourceColumn = ColumnNames.SystemUserRoleID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SystemUserRoleID);
			p.SourceColumn = ColumnNames.SystemUserRoleID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SystemUserID);
			p.SourceColumn = ColumnNames.SystemUserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SystetRoleID);
			p.SourceColumn = ColumnNames.SystetRoleID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifyDate);
			p.SourceColumn = ColumnNames.ModifyDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
