
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _TestGroupsLevelDescriptions : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _TestGroupsLevelDescriptions()
		{
			this.QuerySource = "TestGroupsLevelDescriptions";
			this.MappingName = "TestGroupsLevelDescriptions";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TestGroupsLevelDescriptionsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int TestGroupsLevelDescriptionID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.TestGroupsLevelDescriptionID, TestGroupsLevelDescriptionID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TestGroupsLevelDescriptionsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter TestGroupsLevelDescriptionID
			{
				get
				{
					return new SqlParameter("@TestGroupsLevelDescriptionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter TestGroupID
			{
				get
				{
					return new SqlParameter("@TestGroupID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter TestLevelID
			{
				get
				{
					return new SqlParameter("@TestLevelID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string TestGroupsLevelDescriptionID = "TestGroupsLevelDescriptionID";
            public const string TestGroupID = "TestGroupID";
            public const string TestLevelID = "TestLevelID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TestGroupsLevelDescriptionID] = _TestGroupsLevelDescriptions.PropertyNames.TestGroupsLevelDescriptionID;
					ht[TestGroupID] = _TestGroupsLevelDescriptions.PropertyNames.TestGroupID;
					ht[TestLevelID] = _TestGroupsLevelDescriptions.PropertyNames.TestLevelID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string TestGroupsLevelDescriptionID = "TestGroupsLevelDescriptionID";
            public const string TestGroupID = "TestGroupID";
            public const string TestLevelID = "TestLevelID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TestGroupsLevelDescriptionID] = _TestGroupsLevelDescriptions.ColumnNames.TestGroupsLevelDescriptionID;
					ht[TestGroupID] = _TestGroupsLevelDescriptions.ColumnNames.TestGroupID;
					ht[TestLevelID] = _TestGroupsLevelDescriptions.ColumnNames.TestLevelID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string TestGroupsLevelDescriptionID = "s_TestGroupsLevelDescriptionID";
            public const string TestGroupID = "s_TestGroupID";
            public const string TestLevelID = "s_TestLevelID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int TestGroupsLevelDescriptionID
	    {
			get
	        {
				return base.Getint(ColumnNames.TestGroupsLevelDescriptionID);
			}
			set
	        {
				base.Setint(ColumnNames.TestGroupsLevelDescriptionID, value);
			}
		}

		public virtual int TestGroupID
	    {
			get
	        {
				return base.Getint(ColumnNames.TestGroupID);
			}
			set
	        {
				base.Setint(ColumnNames.TestGroupID, value);
			}
		}

		public virtual int TestLevelID
	    {
			get
	        {
				return base.Getint(ColumnNames.TestLevelID);
			}
			set
	        {
				base.Setint(ColumnNames.TestLevelID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_TestGroupsLevelDescriptionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TestGroupsLevelDescriptionID) ? string.Empty : base.GetintAsString(ColumnNames.TestGroupsLevelDescriptionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TestGroupsLevelDescriptionID);
				else
					this.TestGroupsLevelDescriptionID = base.SetintAsString(ColumnNames.TestGroupsLevelDescriptionID, value);
			}
		}

		public virtual string s_TestGroupID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TestGroupID) ? string.Empty : base.GetintAsString(ColumnNames.TestGroupID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TestGroupID);
				else
					this.TestGroupID = base.SetintAsString(ColumnNames.TestGroupID, value);
			}
		}

		public virtual string s_TestLevelID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TestLevelID) ? string.Empty : base.GetintAsString(ColumnNames.TestLevelID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TestLevelID);
				else
					this.TestLevelID = base.SetintAsString(ColumnNames.TestLevelID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter TestGroupsLevelDescriptionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TestGroupsLevelDescriptionID, Parameters.TestGroupsLevelDescriptionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TestGroupID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TestGroupID, Parameters.TestGroupID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TestLevelID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TestLevelID, Parameters.TestLevelID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter TestGroupsLevelDescriptionID
		    {
				get
		        {
					if(_TestGroupsLevelDescriptionID_W == null)
	        	    {
						_TestGroupsLevelDescriptionID_W = TearOff.TestGroupsLevelDescriptionID;
					}
					return _TestGroupsLevelDescriptionID_W;
				}
			}

			public WhereParameter TestGroupID
		    {
				get
		        {
					if(_TestGroupID_W == null)
	        	    {
						_TestGroupID_W = TearOff.TestGroupID;
					}
					return _TestGroupID_W;
				}
			}

			public WhereParameter TestLevelID
		    {
				get
		        {
					if(_TestLevelID_W == null)
	        	    {
						_TestLevelID_W = TearOff.TestLevelID;
					}
					return _TestLevelID_W;
				}
			}

			private WhereParameter _TestGroupsLevelDescriptionID_W = null;
			private WhereParameter _TestGroupID_W = null;
			private WhereParameter _TestLevelID_W = null;

			public void WhereClauseReset()
			{
				_TestGroupsLevelDescriptionID_W = null;
				_TestGroupID_W = null;
				_TestLevelID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter TestGroupsLevelDescriptionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TestGroupsLevelDescriptionID, Parameters.TestGroupsLevelDescriptionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TestGroupID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TestGroupID, Parameters.TestGroupID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TestLevelID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TestLevelID, Parameters.TestLevelID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter TestGroupsLevelDescriptionID
		    {
				get
		        {
					if(_TestGroupsLevelDescriptionID_W == null)
	        	    {
						_TestGroupsLevelDescriptionID_W = TearOff.TestGroupsLevelDescriptionID;
					}
					return _TestGroupsLevelDescriptionID_W;
				}
			}

			public AggregateParameter TestGroupID
		    {
				get
		        {
					if(_TestGroupID_W == null)
	        	    {
						_TestGroupID_W = TearOff.TestGroupID;
					}
					return _TestGroupID_W;
				}
			}

			public AggregateParameter TestLevelID
		    {
				get
		        {
					if(_TestLevelID_W == null)
	        	    {
						_TestLevelID_W = TearOff.TestLevelID;
					}
					return _TestLevelID_W;
				}
			}

			private AggregateParameter _TestGroupsLevelDescriptionID_W = null;
			private AggregateParameter _TestGroupID_W = null;
			private AggregateParameter _TestLevelID_W = null;

			public void AggregateClauseReset()
			{
				_TestGroupsLevelDescriptionID_W = null;
				_TestGroupID_W = null;
				_TestLevelID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TestGroupsLevelDescriptionsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.TestGroupsLevelDescriptionID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TestGroupsLevelDescriptionsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TestGroupsLevelDescriptionsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.TestGroupsLevelDescriptionID);
			p.SourceColumn = ColumnNames.TestGroupsLevelDescriptionID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.TestGroupsLevelDescriptionID);
			p.SourceColumn = ColumnNames.TestGroupsLevelDescriptionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TestGroupID);
			p.SourceColumn = ColumnNames.TestGroupID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TestLevelID);
			p.SourceColumn = ColumnNames.TestLevelID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
