
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _UserPlacementPreferences : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _UserPlacementPreferences()
		{
			this.QuerySource = "UserPlacementPreferences";
			this.MappingName = "UserPlacementPreferences";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserPlacementPreferencesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int PlacementPreferencesID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.PlacementPreferencesID, PlacementPreferencesID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserPlacementPreferencesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter PlacementPreferencesID
			{
				get
				{
					return new SqlParameter("@PlacementPreferencesID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PlaceTypeCode
			{
				get
				{
					return new SqlParameter("@PlaceTypeCode", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PlaceID
			{
				get
				{
					return new SqlParameter("@PlaceID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter OtherPlace
			{
				get
				{
					return new SqlParameter("@OtherPlace", SqlDbType.NVarChar, 128);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string PlacementPreferencesID = "PlacementPreferencesID";
            public const string UserID = "UserID";
            public const string PlaceTypeCode = "PlaceTypeCode";
            public const string PlaceID = "PlaceID";
            public const string OtherPlace = "OtherPlace";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PlacementPreferencesID] = _UserPlacementPreferences.PropertyNames.PlacementPreferencesID;
					ht[UserID] = _UserPlacementPreferences.PropertyNames.UserID;
					ht[PlaceTypeCode] = _UserPlacementPreferences.PropertyNames.PlaceTypeCode;
					ht[PlaceID] = _UserPlacementPreferences.PropertyNames.PlaceID;
					ht[OtherPlace] = _UserPlacementPreferences.PropertyNames.OtherPlace;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string PlacementPreferencesID = "PlacementPreferencesID";
            public const string UserID = "UserID";
            public const string PlaceTypeCode = "PlaceTypeCode";
            public const string PlaceID = "PlaceID";
            public const string OtherPlace = "OtherPlace";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PlacementPreferencesID] = _UserPlacementPreferences.ColumnNames.PlacementPreferencesID;
					ht[UserID] = _UserPlacementPreferences.ColumnNames.UserID;
					ht[PlaceTypeCode] = _UserPlacementPreferences.ColumnNames.PlaceTypeCode;
					ht[PlaceID] = _UserPlacementPreferences.ColumnNames.PlaceID;
					ht[OtherPlace] = _UserPlacementPreferences.ColumnNames.OtherPlace;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string PlacementPreferencesID = "s_PlacementPreferencesID";
            public const string UserID = "s_UserID";
            public const string PlaceTypeCode = "s_PlaceTypeCode";
            public const string PlaceID = "s_PlaceID";
            public const string OtherPlace = "s_OtherPlace";

		}
		#endregion		
		
		#region Properties
	
		public virtual int PlacementPreferencesID
	    {
			get
	        {
				return base.Getint(ColumnNames.PlacementPreferencesID);
			}
			set
	        {
				base.Setint(ColumnNames.PlacementPreferencesID, value);
			}
		}

		public virtual int UserID
	    {
			get
	        {
				return base.Getint(ColumnNames.UserID);
			}
			set
	        {
				base.Setint(ColumnNames.UserID, value);
			}
		}

		public virtual int PlaceTypeCode
	    {
			get
	        {
				return base.Getint(ColumnNames.PlaceTypeCode);
			}
			set
	        {
				base.Setint(ColumnNames.PlaceTypeCode, value);
			}
		}

		public virtual int PlaceID
	    {
			get
	        {
				return base.Getint(ColumnNames.PlaceID);
			}
			set
	        {
				base.Setint(ColumnNames.PlaceID, value);
			}
		}

		public virtual string OtherPlace
	    {
			get
	        {
				return base.Getstring(ColumnNames.OtherPlace);
			}
			set
	        {
				base.Setstring(ColumnNames.OtherPlace, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_PlacementPreferencesID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PlacementPreferencesID) ? string.Empty : base.GetintAsString(ColumnNames.PlacementPreferencesID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PlacementPreferencesID);
				else
					this.PlacementPreferencesID = base.SetintAsString(ColumnNames.PlacementPreferencesID, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetintAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetintAsString(ColumnNames.UserID, value);
			}
		}

		public virtual string s_PlaceTypeCode
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PlaceTypeCode) ? string.Empty : base.GetintAsString(ColumnNames.PlaceTypeCode);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PlaceTypeCode);
				else
					this.PlaceTypeCode = base.SetintAsString(ColumnNames.PlaceTypeCode, value);
			}
		}

		public virtual string s_PlaceID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PlaceID) ? string.Empty : base.GetintAsString(ColumnNames.PlaceID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PlaceID);
				else
					this.PlaceID = base.SetintAsString(ColumnNames.PlaceID, value);
			}
		}

		public virtual string s_OtherPlace
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.OtherPlace) ? string.Empty : base.GetstringAsString(ColumnNames.OtherPlace);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.OtherPlace);
				else
					this.OtherPlace = base.SetstringAsString(ColumnNames.OtherPlace, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter PlacementPreferencesID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PlacementPreferencesID, Parameters.PlacementPreferencesID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PlaceTypeCode
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PlaceTypeCode, Parameters.PlaceTypeCode);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PlaceID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PlaceID, Parameters.PlaceID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter OtherPlace
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.OtherPlace, Parameters.OtherPlace);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter PlacementPreferencesID
		    {
				get
		        {
					if(_PlacementPreferencesID_W == null)
	        	    {
						_PlacementPreferencesID_W = TearOff.PlacementPreferencesID;
					}
					return _PlacementPreferencesID_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public WhereParameter PlaceTypeCode
		    {
				get
		        {
					if(_PlaceTypeCode_W == null)
	        	    {
						_PlaceTypeCode_W = TearOff.PlaceTypeCode;
					}
					return _PlaceTypeCode_W;
				}
			}

			public WhereParameter PlaceID
		    {
				get
		        {
					if(_PlaceID_W == null)
	        	    {
						_PlaceID_W = TearOff.PlaceID;
					}
					return _PlaceID_W;
				}
			}

			public WhereParameter OtherPlace
		    {
				get
		        {
					if(_OtherPlace_W == null)
	        	    {
						_OtherPlace_W = TearOff.OtherPlace;
					}
					return _OtherPlace_W;
				}
			}

			private WhereParameter _PlacementPreferencesID_W = null;
			private WhereParameter _UserID_W = null;
			private WhereParameter _PlaceTypeCode_W = null;
			private WhereParameter _PlaceID_W = null;
			private WhereParameter _OtherPlace_W = null;

			public void WhereClauseReset()
			{
				_PlacementPreferencesID_W = null;
				_UserID_W = null;
				_PlaceTypeCode_W = null;
				_PlaceID_W = null;
				_OtherPlace_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter PlacementPreferencesID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PlacementPreferencesID, Parameters.PlacementPreferencesID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PlaceTypeCode
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PlaceTypeCode, Parameters.PlaceTypeCode);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PlaceID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PlaceID, Parameters.PlaceID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter OtherPlace
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.OtherPlace, Parameters.OtherPlace);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter PlacementPreferencesID
		    {
				get
		        {
					if(_PlacementPreferencesID_W == null)
	        	    {
						_PlacementPreferencesID_W = TearOff.PlacementPreferencesID;
					}
					return _PlacementPreferencesID_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public AggregateParameter PlaceTypeCode
		    {
				get
		        {
					if(_PlaceTypeCode_W == null)
	        	    {
						_PlaceTypeCode_W = TearOff.PlaceTypeCode;
					}
					return _PlaceTypeCode_W;
				}
			}

			public AggregateParameter PlaceID
		    {
				get
		        {
					if(_PlaceID_W == null)
	        	    {
						_PlaceID_W = TearOff.PlaceID;
					}
					return _PlaceID_W;
				}
			}

			public AggregateParameter OtherPlace
		    {
				get
		        {
					if(_OtherPlace_W == null)
	        	    {
						_OtherPlace_W = TearOff.OtherPlace;
					}
					return _OtherPlace_W;
				}
			}

			private AggregateParameter _PlacementPreferencesID_W = null;
			private AggregateParameter _UserID_W = null;
			private AggregateParameter _PlaceTypeCode_W = null;
			private AggregateParameter _PlaceID_W = null;
			private AggregateParameter _OtherPlace_W = null;

			public void AggregateClauseReset()
			{
				_PlacementPreferencesID_W = null;
				_UserID_W = null;
				_PlaceTypeCode_W = null;
				_PlaceID_W = null;
				_OtherPlace_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserPlacementPreferencesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.PlacementPreferencesID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserPlacementPreferencesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserPlacementPreferencesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.PlacementPreferencesID);
			p.SourceColumn = ColumnNames.PlacementPreferencesID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.PlacementPreferencesID);
			p.SourceColumn = ColumnNames.PlacementPreferencesID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PlaceTypeCode);
			p.SourceColumn = ColumnNames.PlaceTypeCode;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PlaceID);
			p.SourceColumn = ColumnNames.PlaceID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.OtherPlace);
			p.SourceColumn = ColumnNames.OtherPlace;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
