
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using PIKCV.DAO;

namespace PIKCV.DAL
{
	public abstract class _UserTestPerfectionResults : SqlClientEntity
	{
		private string m_SchemaStoredProcedure = "Pikcv].[";
		public _UserTestPerfectionResults()
		{
			this.QuerySource = "UserTestPerfectionResults";
			this.MappingName = "UserTestPerfectionResults";

		this.SchemaStoredProcedure = m_SchemaStoredProcedure;
		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserTestPerfectionResultsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int UserTestPerfectionResultID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.UserTestPerfectionResultID, UserTestPerfectionResultID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserTestPerfectionResultsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter UserTestPerfectionResultID
			{
				get
				{
					return new SqlParameter("@UserTestPerfectionResultID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter TestPerfectionID
			{
				get
				{
					return new SqlParameter("@TestPerfectionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AnswerPoint
			{
				get
				{
					return new SqlParameter("@AnswerPoint", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string UserTestPerfectionResultID = "UserTestPerfectionResultID";
            public const string UserID = "UserID";
            public const string TestPerfectionID = "TestPerfectionID";
            public const string AnswerPoint = "AnswerPoint";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UserTestPerfectionResultID] = _UserTestPerfectionResults.PropertyNames.UserTestPerfectionResultID;
					ht[UserID] = _UserTestPerfectionResults.PropertyNames.UserID;
					ht[TestPerfectionID] = _UserTestPerfectionResults.PropertyNames.TestPerfectionID;
					ht[AnswerPoint] = _UserTestPerfectionResults.PropertyNames.AnswerPoint;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string UserTestPerfectionResultID = "UserTestPerfectionResultID";
            public const string UserID = "UserID";
            public const string TestPerfectionID = "TestPerfectionID";
            public const string AnswerPoint = "AnswerPoint";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UserTestPerfectionResultID] = _UserTestPerfectionResults.ColumnNames.UserTestPerfectionResultID;
					ht[UserID] = _UserTestPerfectionResults.ColumnNames.UserID;
					ht[TestPerfectionID] = _UserTestPerfectionResults.ColumnNames.TestPerfectionID;
					ht[AnswerPoint] = _UserTestPerfectionResults.ColumnNames.AnswerPoint;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string UserTestPerfectionResultID = "s_UserTestPerfectionResultID";
            public const string UserID = "s_UserID";
            public const string TestPerfectionID = "s_TestPerfectionID";
            public const string AnswerPoint = "s_AnswerPoint";

		}
		#endregion		
		
		#region Properties
	
		public virtual int UserTestPerfectionResultID
	    {
			get
	        {
				return base.Getint(ColumnNames.UserTestPerfectionResultID);
			}
			set
	        {
				base.Setint(ColumnNames.UserTestPerfectionResultID, value);
			}
		}

		public virtual int UserID
	    {
			get
	        {
				return base.Getint(ColumnNames.UserID);
			}
			set
	        {
				base.Setint(ColumnNames.UserID, value);
			}
		}

		public virtual int TestPerfectionID
	    {
			get
	        {
				return base.Getint(ColumnNames.TestPerfectionID);
			}
			set
	        {
				base.Setint(ColumnNames.TestPerfectionID, value);
			}
		}

		public virtual int AnswerPoint
	    {
			get
	        {
				return base.Getint(ColumnNames.AnswerPoint);
			}
			set
	        {
				base.Setint(ColumnNames.AnswerPoint, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_UserTestPerfectionResultID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserTestPerfectionResultID) ? string.Empty : base.GetintAsString(ColumnNames.UserTestPerfectionResultID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserTestPerfectionResultID);
				else
					this.UserTestPerfectionResultID = base.SetintAsString(ColumnNames.UserTestPerfectionResultID, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetintAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetintAsString(ColumnNames.UserID, value);
			}
		}

		public virtual string s_TestPerfectionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TestPerfectionID) ? string.Empty : base.GetintAsString(ColumnNames.TestPerfectionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TestPerfectionID);
				else
					this.TestPerfectionID = base.SetintAsString(ColumnNames.TestPerfectionID, value);
			}
		}

		public virtual string s_AnswerPoint
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AnswerPoint) ? string.Empty : base.GetintAsString(ColumnNames.AnswerPoint);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AnswerPoint);
				else
					this.AnswerPoint = base.SetintAsString(ColumnNames.AnswerPoint, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter UserTestPerfectionResultID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserTestPerfectionResultID, Parameters.UserTestPerfectionResultID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TestPerfectionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TestPerfectionID, Parameters.TestPerfectionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AnswerPoint
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AnswerPoint, Parameters.AnswerPoint);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter UserTestPerfectionResultID
		    {
				get
		        {
					if(_UserTestPerfectionResultID_W == null)
	        	    {
						_UserTestPerfectionResultID_W = TearOff.UserTestPerfectionResultID;
					}
					return _UserTestPerfectionResultID_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public WhereParameter TestPerfectionID
		    {
				get
		        {
					if(_TestPerfectionID_W == null)
	        	    {
						_TestPerfectionID_W = TearOff.TestPerfectionID;
					}
					return _TestPerfectionID_W;
				}
			}

			public WhereParameter AnswerPoint
		    {
				get
		        {
					if(_AnswerPoint_W == null)
	        	    {
						_AnswerPoint_W = TearOff.AnswerPoint;
					}
					return _AnswerPoint_W;
				}
			}

			private WhereParameter _UserTestPerfectionResultID_W = null;
			private WhereParameter _UserID_W = null;
			private WhereParameter _TestPerfectionID_W = null;
			private WhereParameter _AnswerPoint_W = null;

			public void WhereClauseReset()
			{
				_UserTestPerfectionResultID_W = null;
				_UserID_W = null;
				_TestPerfectionID_W = null;
				_AnswerPoint_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter UserTestPerfectionResultID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserTestPerfectionResultID, Parameters.UserTestPerfectionResultID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TestPerfectionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TestPerfectionID, Parameters.TestPerfectionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AnswerPoint
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AnswerPoint, Parameters.AnswerPoint);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter UserTestPerfectionResultID
		    {
				get
		        {
					if(_UserTestPerfectionResultID_W == null)
	        	    {
						_UserTestPerfectionResultID_W = TearOff.UserTestPerfectionResultID;
					}
					return _UserTestPerfectionResultID_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public AggregateParameter TestPerfectionID
		    {
				get
		        {
					if(_TestPerfectionID_W == null)
	        	    {
						_TestPerfectionID_W = TearOff.TestPerfectionID;
					}
					return _TestPerfectionID_W;
				}
			}

			public AggregateParameter AnswerPoint
		    {
				get
		        {
					if(_AnswerPoint_W == null)
	        	    {
						_AnswerPoint_W = TearOff.AnswerPoint;
					}
					return _AnswerPoint_W;
				}
			}

			private AggregateParameter _UserTestPerfectionResultID_W = null;
			private AggregateParameter _UserID_W = null;
			private AggregateParameter _TestPerfectionID_W = null;
			private AggregateParameter _AnswerPoint_W = null;

			public void AggregateClauseReset()
			{
				_UserTestPerfectionResultID_W = null;
				_UserID_W = null;
				_TestPerfectionID_W = null;
				_AnswerPoint_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserTestPerfectionResultsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.UserTestPerfectionResultID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserTestPerfectionResultsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserTestPerfectionResultsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.UserTestPerfectionResultID);
			p.SourceColumn = ColumnNames.UserTestPerfectionResultID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.UserTestPerfectionResultID);
			p.SourceColumn = ColumnNames.UserTestPerfectionResultID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TestPerfectionID);
			p.SourceColumn = ColumnNames.TestPerfectionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AnswerPoint);
			p.SourceColumn = ColumnNames.AnswerPoint;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
